(function(){var g=void 0,h=true,i=null,j=false,k,m=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function n(a,b){function c(){}c.prototype=b.prototype;a.U=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ba(){}
function ca(a,b,c){switch(typeof b){case "string":da(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==i){c.push("null");break}if(aa(b)=="array"){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),ca(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],typeof f!="function"&&(c.push(d),da(e,c),c.push(":"),ca(a,f,c),d=","));
c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var ea={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},fa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function da(a,b){b.push('"',a.replace(fa,function(a){if(a in ea)return ea[a];var b=a.charCodeAt(0),e="\\u";b<16?e+="000":b<256?e+="00":b<4096&&(e+="0");return ea[a]=e+b.toString(16)}),'"')};var ga=/[?&]__cb_debug=([^&]+)/i,ha={scroll:5E3,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3},ia={scroll:2E4,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3},ja=/:\/\/static2\.chartbeat.com\/js\/chartbeat(_[a-z]+)?\.js$/;function ka(a,b){var c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}function la(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function p(a,b){var c="",d=ma(encodeURIComponent(a));d.splice(b||5,d.length);r(d,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",d;a>0;)d=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(d)+b,a>>>=6;a=b}c+=a});return c}
function ma(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,l=3285377520,o=[],q,v,z,L,M,$=Math.ceil((a.length/4+2)/16),W=[$],A=0,x;A<$;A++){W[A]=[];for(q=0;q<16;q++)W[A][q]=a.charCodeAt(A*64+q*4)<<24|a.charCodeAt(A*64+q*4+1)<<16|a.charCodeAt(A*64+q*4+2)<<8|a.charCodeAt(A*64+q*4+3)}A=(a.length-1)*8;a=$-1;W[a][14]=Math.floor(A/Math.pow(2,32));W[a][15]=A&4294967295;for(A=0;A<$;A++){for(x=0;x<16;x++)o[x]=W[A][x];
for(x=16;x<80;x++)o[x]=(o[x-3]^o[x-8]^o[x-14]^o[x-16])<<1|(o[x-3]^o[x-8]^o[x-14]^o[x-16])>>>31;a=c;q=d;v=e;z=f;L=l;for(x=0;x<80;x++)M=Math.floor(x/20),M=(a<<5|a>>>27)+(M==0?q&v^~q&z:M==1?q^v^z:M==2?q&v^q&z^v&z:q^v^z)+L+b[M]+o[x]&4294967295,L=z,z=v,v=q<<30|q>>>2,q=a,a=M;c=c+a&4294967295;d=d+q&4294967295;e=e+v&4294967295;f=f+z&4294967295;l=l+L&4294967295}return[c,d,e,f,l]}
function na(a){var b=m.navigator,c=m.window.screen,d=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];r(b.plugins,function(a){d.push(a.name+a.description+a.filename+a[0].type)});b=m.performance;d=d.concat([b&&b.now?b.now():"",document.title,m.location.href,s(),la()]);return d.concat(a||[]).join()}function t(a,b,c){var d=Array.prototype.slice,e=d.call(arguments,2);return function(){return a.apply(b,e.concat(d.call(arguments)))}}
function u(a){return typeof a!=="undefined"}function oa(a){return a.replace(/^www\./,"")}var pa=/^((https?\:)?(\/\/))/i;function qa(a){return a.replace(pa,"")}var ra=/^((https?\:)?(\/\/))?[^\/]*/;function sa(a){return a.replace(ra,"")}var ta=/\#.*/;function ua(a){return a.replace(ta,"")}var va=/\?[^\#]*/;function wa(a){return a.toLowerCase()}var xa=/\/+((\?|\#).*)?$/;function ya(a){return a.replace(xa,"$1")}function za(a){return a.replace(va,"")}
function Aa(a,b){if(a===b)return 0;var c=i;r([wa,ya,qa,sa,ua,za],function(d,e){a=d(a);b=d(b);if(a===b)return c=e+1,j});return c}function w(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)}function Ba(a,b){var c=m;c.removeEventListener?c.removeEventListener(a,b,j):c.detachEvent&&c.detachEvent("on"+a,b)}function Ca(a){return typeof a==="number"}function y(a){return typeof a==="string"}
function Da(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function s(){return(new Date).getTime()}function Ea(a){return encodeURIComponent(a)}function Fa(){return m.location.protocol==="https:"?"https:":"http:"}function B(a){return!!a&&a.constructor===Object}function Ga(a,b){if(!B(a)||!B(b))return a===b;var c=0,d=h;r(a,function(a,e){c++;return d=a===b[e]});if(!d)return j;var e=0;r(b,function(){e++});return c===e}
function r(a,b){if(B(a)===h)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===j)break}}function Ha(a,b){var c=[];r(a,function(a,e){var f=b(a,e);c.push(f)});return c}function Ia(a,b){for(var c=0,d=a.length;c<d;c++)if(b(a[c]))return c;return-1}function Ja(a){if(B(a)===j)return"";var b=[];r(a,function(a,d){b.push(encodeURIComponent(d)+"::"+encodeURIComponent(a))});return b.join("&")}
function Ka(a){y(a)||(a="");var b={};r(a.split("&"),function(a){a=a.split("::");a.length===2&&(b[decodeURIComponent(a[0])]=decodeURIComponent(a[1]))});return b}
function La(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,e=b.length;d<=e;d++)c[d]=[d];for(var f=0,l=a.length;f<=l;f++)c[0][f]=f;for(var o,q,v,d=1;d<=e;d++)for(f=1;f<=l;f++)o=d-1,q=f-1,v=c[o][q],b.charAt(o)==a.charAt(q)?c[d][f]=v:(q=c[d][q]+1,o=c[o][f]+1,v+=2,c[d][f]=Math.min(q,o,v));return c[b.length][a.length]}var Ma;function Na(){}var Oa=m.setInterval,Pa=m.clearInterval,Qa=m.setTimeout,C=m.clearTimeout;
function Ra(a,b){var c={};r(b,function(b,e){c[b]=t(a[e],a)});return c}function Sa(a){var b=[];if(!B(a))return b;for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b}function Ta(a){switch(a){case g:return"undefined";case "":return"empty";default:return a}};function Ua(a,b,c){b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");for(var d=[],b=c.getElementsByTagName(b),c=b.length;c--;)b[c].getAttribute(a)&&d.push(b[c]);return d}function D(a,b){var c=i;b&&(c=b.getAttribute(a));if(c===i){var d=Ua(a,"*",b);d.length!==0&&(c=d[0].getAttribute(a))}return c}
function Va(a,b,c){c=c||"";if(a===g)a=j;else{var d;if(!(d=c===""&&a.getAttribute(b)))if(d=a.getAttribute(b))d=a.getAttribute(b)===c;a=d?a:a===document.body?j:Va(a.parentNode,b,c)}return a}function Wa(a,b,c){a="page"+a+"Offset";b="scroll"+b;if(c&&(c=Ua("data-cb-scroll-element"))&&c.length)return c[0][b];if(Ca(m[a]))return m[a];else if(document.body&&document.body[b])return document.body[b];else if(document.documentElement[b])return document.documentElement[b];return 0}
function Xa(a){var b=document,b=b[b.compatMode==="CSS1Compat"?"documentElement":"body"]["client"+a]||0;window["inner"+a]&&(b=Math.min(window["inner"+a],b));return b}function Ya(){return Xa("Height")}function Za(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}
function $a(a,b,c){a.ownerDocument||(a=a.correspondingUseElement);if(!a||!a.ownerDocument)return i;var d=a.ownerDocument.documentElement,e=0,f=u(c)?c+1:-1;y(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==d&&e!==f;){if(c(a))return a;a=a.parentNode;e++}return i}function ab(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}
function bb(a){a=a||window.event;return!a?i:$a(a.target||a.srcElement,ab,10)}function cb(a,b){var c=document.createElement(a);r(b,function(a,b){c.setAttribute(b,a)});return c}function db(a){var b=u(g)?g:{};b.src=a;a=cb("script",b);a.setAttribute("type","text/javascript");b=document.head||document.getElementsByTagName("head")[0];u(g)?g.appendChild(a):b&&b.appendChild(a)}
function eb(){if(u(fb))return fb;var a;a:{a=document.getElementsByTagName("script");for(var b=a.length-1;b>-1;b--)if(ja.test(a[b].getAttribute("src"))){a=a[b];break a}a=g}return fb=u(a)}var fb;function gb(){this.Y={};this.Ib=1}k=gb.prototype;k.M=function(a,b,c){this.Ib++;this.Y[a]=this.Y[a]||{};this.Y[a][this.Ib]=[b,c];return this.Ib};k.T=function(a){if(y(a))this.Y[a]=g,delete this.Y[a];else if(Ca(a)){var b=h;r(this.Y,function(c){r(c,function(d,e){if(parseInt(e,10)===a)return c[e]=g,delete c[e],b=j});return b})}};k.S=function(a,b){if(this.Y[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];r(this.Y[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
k.addEventListener=function(a,b){var c=this.M(a,b);b._cbEventId=c};k.removeEventListener=function(a,b){this.Y[a]&&this.Y[a][b._cbEventId]&&this.Y[a][b._cbEventId][0]===b&&this.T(b._cbEventId)};var E=new gb,hb="o",ib={M:hb,T:"f"},jb="a";var F={};
F.q=function(){F.ub?F.Ua("pageload"):(F.qc=[{target:m,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:m,event:"resize"},{target:document.body,event:"mousedown"}],F.eb=i,F.la=i,F.tb={},F.sb={},F.dc={},F.fb={},r(F.qc,function(a){var b=a.event;w(a.target,b,function(a){F.Ua.call(F,b,a)})}),E.M("f",function(){F.Ua("focus")}),F.Ua("pageload"),w(document.body,"click",function(a){(a=bb(a))&&E.S("c",a)},h),w(document.body,"contextmenu",function(a){(a=bb(a))&&
E.S("r",a)}),F.ub=h)};F.vc=function(){var a,b=F.dc.keydown;if(b===g)return j;b=s()-b;return b<=(a||15E3)&&b>=0};F.Da=function(a,b){var c=F.fb[a];if(!c)return"";var b=b||s(),d,e=0;r(c,function(a){d=Math.floor((b-a)/1E3);d>=0&&d<16&&(e|=1<<d)});c=("0000"+e.toString(16)).slice(-4);return c=="0000"?"":c};F.$c=function(){F.fb={}};F.Ob=100;
F.Ua=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}F.gd(a);if(F.eb===i)F.lc(a);else if(!F.la||ha[F.la]<ha[a]||ia[F.la]<ia[a])F.la=a};F.gd=function(a){var b=s();F.dc[a]=b;var c=F.fb[a];c?c.length<2?c.push(b):c[c.length-2]>b-1E3?c[c.length-1]=b:c.push(b):c=[b];c.length>32&&c.shift();F.fb[a]=c};F.lc=function(a){F.eb=Qa(F.zc,F.Ob);E.S(jb);F.tb[a]!==i&&C(F.tb[a]);F.sb[a]!==i&&C(F.sb[a]);F.jc(a,F.tb,ha,"i");F.jc(a,F.sb,ia,"j")};
F.jc=function(a,b,c,d){b[a]=Qa(function(){C(b[a]);delete b[a];var c=j;r(b,function(){c=h;return j});c||E.S(d)},c[a]+F.Ob)};F.zc=function(){C(F.eb);F.eb=i;if(F.la)F.lc(F.la),F.la=i};var kb,lb,mb,nb,ob;(function(){var a,b;r(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof m.document[a]==="boolean")return b=c,j});b!==g&&(nb=a,ob=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),mb=b+"visibilitychange")})();var pb=j;function qb(){pb=ob&&m.document[ob]==="prerender"?h:j}function rb(){lb=h;E.S("f")}function sb(){lb=j;E.S("b")}
function tb(a,b,c){m.addEventListener?m.addEventListener(a,c,j):m.document.attachEvent&&m.document.attachEvent(b,c)}function ub(){var a=h;m.document.hasFocus&&(a=m.document.hasFocus());var b=j;nb&&(b=m.document[nb]);return a&&!b}function vb(){ub()?rb():sb()}function wb(a){qb();if(pb){var b=j,c=function(){b||(qb(),pb||(b=h,a(),m.window.setTimeout(function(){m.document.removeEventListener(mb,c,j)},100)))};m.document.addEventListener(mb,c,j)}else a()};function G(){this.k=m._sf_async_config||{};this.Ub=t(this.hc,this)}G.prototype.q=function(){this.Db=0};G.prototype.hc=function(){};G.prototype.Ka=function(a){pb||ka(a,this.Ub)};G.prototype.ba=function(){this.Ub=i};function xb(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace("+"," "),r(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function yb(a,b){var c="",d=m.location.href.split("?");if(d.length){var d=xb(d[1]),e=b||a;d[e]&&(c=d[e])}return c}function zb(a,b){return!b?h:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function Ab(a,b){var c=[];r(b,function(b){var e=a[b];u(e)&&(Object.prototype.toString.call(e)==="[object Array]"?r(e,function(a){c.push(b+"="+a)}):B(e)?r(e,function(a,b){c.push(b+"="+a)}):((e+"").length||b=="r")&&c.push(b+"="+e))});c.push("_");return c.join("&")}
function Bb(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),d=m.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0&&a.indexOf("app:")<0)if(a.indexOf("//")===0)a=d.protocol+a;else if(a.indexOf("/")===0)var e=zb(d.protocol,d.port)?"":d.port,a=d.protocol+"//"+d.hostname+(e?":"+e:"")+a;else{var e=document.baseURI||d.href,f=e.indexOf("?");f===-1&&(f=e.indexOf("#"));if(f===-1)f=e.length;f=e.lastIndexOf("/",f);a=f===-1?
"/"+a:e.substr(0,f)+"/"+a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=d.hostname;if(b.protocol==="")b.protocol=d.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(zb(b.protocol,b.port)||b.port==="0")b.port="";return b}
function Cb(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash}function Db(){var a=0,b=(m.location.search||"").match(ga);b&&b[1]&&(a=parseInt(b[1],10));return a};var Eb="adIdentifier";function H(a,b,c){a[b]=a[b]||c}function Fb(a,b){for(var c=m[a]||[];c.length;)b(c.shift());m[a]={push:b}}function Gb(a){r(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=xb(b.src.split("?")[1]),H(a,"uid",b.uid),H(a,"domain",b.domain),j})}function Hb(a,b){return a[b]?encodeURIComponent(a[b]):""}function Ib(a){var b={};r(a,function(a,d){d.charAt(0)=="_"&&(b[d]=a)});return b};function Jb(a){var b=a===document.documentElement?a.scrollHeight:a.offsetHeight,c=a.offsetWidth;if(b<=1||c<=1){var d=Kb(a,["overflow","overflow-x","overflow-y"]);d.overflow==="hidden"||d["overflow-x"]==="hidden"||d["overflow-y"]==="hidden"||r(a.getElementsByTagName("iframe"),function(a){var d=a.offsetHeight,a=a.offsetWidth;if(d>1&&a>1)return b=d,c=a,j})}return{height:b,width:c}}function Lb(a){a=Jb(a);return a.height*a.width}
function Mb(a){var b;"contains"in document.documentElement&&!document.documentElement.contains(a)?b=j:(b=Jb(a),b=b.height>1&&b.width>1);if(!b)return j;b=Kb(a,["visibility","display","overflow","opacity"]);if(b.visibility=="hidden"||b.display=="none"||b.opacity=="0")return j;if(b.overflow=="hidden"&&(a.offsetHeight==0||a.offsetWidth==0))return j;b=h;for(var c=a.parentElement;c&&b;){var d;if(c.scrollHeight===c.clientHeight&&c.scrollWidth===c.clientWidth)d=j;else{var e=Kb(c,["overflow","overflow-x",
"overflow-y"]);d=e.overflow;var f=e["overflow-x"],e=e["overflow-y"];d=d==="auto"||d==="scroll"||f==="auto"||f==="scroll"||e==="auto"||e==="scroll"}d&&(b=Nb(a,c));c=c.parentElement}return b&&Nb(a,i)}function Nb(a,b){var c,d;if(b){var e=Jb(b);c=e.width;d=e.height}else c=Xa("Width"),d=Ya();var f=Jb(a),e=f.height,f=f.width,l=Ob(a,b),o=l.y,l=l.x;c=Math.min(l+f,f,c,c-l);d=Math.min(o+e,e,d,d-o);if(c<0||d<0)return j;e*=f;return c*d>=(e>=242500?0.3:0.5)*e}
function Ob(a,b,c){var d=a.offsetLeft,e=a.offsetTop,f=Pb(a);d+=f.x;e+=f.y;for(var l=j,o=c?0:Math.floor(Wa("X","Left",g)),q=c?0:Math.floor(Wa("Y","Top",g)),f=a.offsetParent;a&&a!==b&&a!==document.body;){if(a===f)f=Pb(a),d+=a.offsetLeft+f.x,e+=a.offsetTop+f.y,f=a.offsetParent;c||(d-=a.scrollLeft,e-=a.scrollTop);if(Kb(a,["position"]).position==="fixed"){l=h;break}a=a.parentElement}c||(d-=b?b.scrollLeft:o,e-=b?b.scrollTop:q);l&&(d+=o,e+=q);return{x:d,y:e}}
function Kb(a,b){var c={},d,e;m.getComputedStyle?d=m.getComputedStyle(a,i):a.currentStyle?e="currentStyle":a.style&&(e="style");r(b,function(b){c[b]=d?d[b]||d.getPropertyValue(b):a[e][b]});return c}var Qb=/matrix(3d)?\((.*)\)/;function Pb(a){var b={x:0,y:0},a=Kb(a,["transform"]).transform;if(!y(a))return b;var c=a.match(Qb);if(!c)return b;var a=c[2].split(", "),d;u(c[1])?(c=12,d=13):(c=4,d=5);b.x=parseInt(a[c],10);b.y=parseInt(a[d],10);return b};var I={},Rb={nb:"g"};I.Pb={IDLE:0,sc:1,rc:2,La:3};I.tc={IDLE:0,sc:1,rc:2,La:3};I.Z=0;I.$=0;I.q=function(){if(!I.ub)E.M(jb,I.Kc,I),E.M("i",I.Pc,I),E.M("f",I.Mc,I),E.M("b",I.Lc,I),E.M("j",I.Oc,I),I.ub=h};I.nb=function(){return I.Z};I.Ic=function(){return I.$};I.Kc=function(){I.Z===1?I.ja(3):I.Z===0&&I.ja(2);I.$===1?I.ia(3):I.$===0&&I.ia(2)};I.Pc=function(){I.Z===3?I.ja(1):I.Z===2&&I.ja(0)};I.Oc=function(){I.$===3?I.ia(1):I.$===2&&I.ia(0)};
I.Mc=function(){(I.Z===0||I.Z===2)&&I.ja(3);(I.$===0||I.$===2)&&I.ia(3)};I.Lc=function(){I.Z===3?I.ja(2):I.Z===1&&I.ja(0);I.$===3?I.ia(2):I.$===1&&I.ia(0)};I.ja=function(a){I.Z=a;E.S("s",a)};I.ia=function(a){I.$=a;E.S("x",a)};function Sb(a,b){this.qb=a||g;this.Ja=b||g;this.ga=this.N=0;this.Yb=t(this.Tc,this);this.Gb=this.aa=i}k=Sb.prototype;k.q=function(){this.ga=this.N=0;this.aa=i;this.Gb=E.M("s",this.Ea,this);this.Ea(I.nb())};k.Ea=function(a){Pa(this.aa);this.aa=i;if(a===I.Pb.La)this.aa=Oa(this.Yb,1E3)};k.Tc=function(){if(this.qb===g||this.qb())this.N++,this.ga++,this.Ja&&this.Ja()};k.terminate=function(){Pa(this.aa);this.aa=i;E.T(this.Gb)};k.ba=function(){this.terminate();this.Ja=this.qb=g};function Tb(){G.call(this);this.Jb=t(this.Jb,this);this.Rb=0;this.kb=Ub;this.q()}n(Tb,G);Tb.prototype.q=function(){Tb.U.q.call(this);this.Rb++;this.G={};this.G.siteId="";this.mb=j;this.Qb=Vb;this.Tb=this.pc=j;this.Lb={};this.oc=j;this.gb=0;this.za=i;this.ld=E.M("s",this.Xb,this);this.Xb(I.nb())};var Ub=0,Vb=0;k=Tb.prototype;k.Xb=function(a){if(this.za!==i)Pa(this.za),this.za=i;this.gb=0;if(a===I.Pb.La)this.za=Oa(this.Jb,100)};
k.Jb=function(){if(Mb(this.Na.Q)){if(this.gb++,this.gb>=10)this.oc=h,Wb(this),E.S("p")}else this.gb=0;this.Bc&&this.Bc.update()};function Wb(a){E.T(a.ld);Pa(a.za);a.za=i}k.$a=function(a){if(a.exclude)this.mb=h;this.Tb=!!a.dynamicLogic;this.G=a;E.S("p");if(a=a.vizu)this.pc=h,this.Lb=Ka(a),E.S("z",this.Lb,this.Na.da.N)};
function Xb(a){var b=encodeURIComponent(a.an),c=a.aE,d=a.ax,e=a.ay,f=a.aw,l=a.ah,o=encodeURIComponent(a.av||""),q=encodeURIComponent(a.ac||""),v=encodeURIComponent(a.aP||""),z=encodeURIComponent(a.aS||""),L=encodeURIComponent(a.aH||""),M=encodeURIComponent(a.aW||""),$=encodeURIComponent(a.aL||""),W=a.ao,A=a.aR,x=a.am,Wc=a.aV?"1":"0";a.exclude&&(q="");return b+"="+[c,d,e,f,l,q,o,W+"."+A,Wc,v,z,L,M,$,x].join("::")}
k.ma=function(a,b){a.siteId=D("data-cb-site-id",b)||"";a.dynamicLogic=D("data-cb-dynamic-logic-id",b)||"";if(D("data-cb-exclude",b))this.mb=h;return a};k.refresh=function(){Wb(this);this.q()};k.ba=function(){Tb.U.ba.call(this);Wb(this)};function J(a){this.P=a;this.qa=a.getAttribute("data-cb-ad-id")||a.id||"";this.ob=1;var b=this;this.da=new Sb(function(){Yb(b);return Mb(b.Q)},t(this.Ja,this));Zb&&this.Ma();this.q()}var Zb;J.prototype.Ja=function(){E.S("e",this);if(this.H){var a=this.H;a.pc&&E.S("z",a.Lb,1)}this.Pa&&this.Pa.update()};
J.prototype.q=function(){this.G={};this.G.campaignId="";this.G.creativeId="";this.G.placementId="";this.G.server_height="";this.G.server_width="";this.G.lineId="";this.Q=this.P;this.Ta=this.vb=this.rb=this.yb=j;this.fa={};this.fa.iab=j;this.fa.frame=j;this.fa.roadblock=j;Yb(this);this.da.q()};J.prototype.Ma=function(){var a=this;this.Pa=new Zb(this.qa,function(){return{adContainer:a.P,creativeContainer:a.Q,creativeScenarios:a.fa,adData:$b(a)}})};
var ac={300:{250:1,600:1,1050:1},180:{150:1},160:{600:1},728:{90:1},970:{90:1,66:1,250:1,415:1,550:1},120:{60:1},88:{31:1},62:{88:1},196:{31:1}};
function Yb(a){var b=m._sf_async_config;if(b&&(b=b.creativeDetection,b===j||y(b)&&b!=="iab"))return;var c=Lb(a.P);if(a.Q!==a.P)if(b=Lb(a.Q),b>c||b===0)a.Q=a.P;else if(b>0)return;r(["iframe","embed","object","img","div"],function(b){r(a.P.getElementsByTagName(b),function(b){var d=Jb(b);if(!(d.height*d.width>c)&&ac[d.width]&&ac[d.width][d.height])return a.Q=b,a.fa.iab=h,j});return a.Q===a.P})}
J.prototype.$a=function(a,b){if(a.noRefresh)this.yb=h;var c=a.roadblock;this.vb=(this.Ta=c==="master")||c==="companion";this.fa.roadblock=c||j;this.G=a;if(this.rb=!!b){if(c=m._sf_async_config)if(c=c.creativeDetection,c===j||y(c)&&c!=="iframe")return;if(Lb(b)>0)this.Q=b,this.fa.frame=h}this.H&&this.H.$a(a)};function K(a,b){return a.G&&u(a.G[b])?a.G[b]:""}var N="engagedSeconds",bc={rd:"id",qd:N,nd:"campaignId",od:"creativeId",sd:"placementId",pd:"element"};
function cc(a){var b={};b.id=a.qa;b[N]=a.da.N;b.campaignId=K(a,"campaignId");b.creativeId=K(a,"creativeId");b.placementId=K(a,"placementId");return b}
function $b(a){var b={};b.an=a.qa;b.aE=a.da.N;if(a.Q){var c=Ob(a.Q,g,h);b.ax=c.x;b.ay=c.y;c=Jb(a.Q);b.aw=c.width;b.ah=c.height}b.ac=K(a,"campaignId");b.av=K(a,"creativeId");b.aP=K(a,"placementId");b.aW=K(a,"server_width");b.aH=K(a,"server_height");b.aL=K(a,"lineId");if(a.H)a=a.H,b.aV=a.oc,b.ao=a.Rb,b.aS=K(a.Na,"siteId"),b.exclude=a.mb,b.am=a.kb,b.aR=a.Qb;return b}
J.prototype.ma=function(){if(!this.rb){var a=this.P,b={};b.campaignId=D("data-cb-campaign-id",a)||"";b.creativeId=D("data-cb-creative-id",a)||"";b.placementId=D("data-cb-placement-id",a)||"";b.server_height=D("data-cb-creative-height",a)||"";b.server_width=D("data-cb-creative-width",a)||"";b.lineId=D("data-cb-line-id",a)||"";b.roadblock=D("data-cb-roadblock",a)||"";this.H&&this.H.ma(b,a);if(D("data-cb-no-refresh",a))this.yb=h;Ga(b,this.G)||this.$a(b)}};
J.prototype.refresh=function(){this.da.terminate();this.H&&this.H.refresh();this.q()};J.prototype.terminate=function(){this.da&&this.da.ba();this.G=this.Q=this.P=i;this.Pa&&this.Pa.dispose();this.H&&this.H.ba()};var O={};O.yc=function(){try{O.create("_cb_test","1",1);var a=O.F("_cb_test");O.remove("_cb_test");return a==="1"}catch(b){return j}};O.F=function(a){a+="=";var b="";r(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),j});return b};
O.create=function(a,b,c){var d=m._sf_async_config;if(d&&d.noCookies)return"";d=new Date;d.setTime(s()+c*1E3);a=a+"="+b+("; expires="+d.toGMTString())+"; path=/";return document.cookie=a};O.remove=function(a){return O.F(a)?O.create(a,"",-86400):""};var P={};P.J=function(a){var b=m._sf_async_config;if(!a&&b&&b.noCookies)return i;if(P.J.lb!==g)return P.J.lb;var a=s()+"",c,d;try{if((d=m.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return P.J.lb=d}catch(e){}return P.J.lb=i};P.F=function(a){var b=P.J();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&s()>c)?(P.remove(a),""):b.getItem(a)||""};
P.create=function(a,b,c){var d=P.J();if(d){var e=new Date;e.setTime(s()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",e.getTime())}catch(f){}}};P.remove=function(a){var b=P.J();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function dc(a){this.Wa=a||"";this.Ac=P.J()!==i||O.yc();this.Hb=j;ec(this)}k=dc.prototype;k.isSupported=function(){return this.Ac};
function ec(a){if(!O.F("_cb_ls")){var b=P.J()!==i,c=O.F("_SUPERFLY_lockout");c&&r(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_lockout",c,600,h)});var d=O.F("_chartbeat3");d&&(a.create("_v__chartbeat3",d,34128E3,h),O.remove("_chartbeat3"));b&&((b=O.F("_chartbeat2"))&&a.create("_chartbeat2",b,34128E3,h),(b=O.F("_chartbeat5"))&&a.create("_chartbeat5",b,60,h));O.create("_cb_ls","1",34128E3)}}function fc(a){var b=a.Hb;a.Hb=j;return b}
k.create=function(a,b,c,d){a=d?a:this.Wa+a;(P.J()?P:O).create(a,b,c);P.J()&&O.create(a,b,c)};k.update=function(a,b,c,d,e,f,l){a=d?a:this.Wa+a;e=y(e)?e:"::";d=(d=this.F(a,h))?d.split(e):[];if(l&&d.length){var o=l(b),q=Ia(d,function(a){return l(a)===o});q!==-1&&d.splice(q,1)}d.push(b);for(Ca(f)&&d.length>f&&d.splice(0,d.length-f);d.length>1&&d.join(e).length>4E3;)d.shift();this.create(a,d.join(e),c,h)};
k.F=function(a,b){var a=b?a:this.Wa+a,c=(P.J()?P:O).F(a);if(!c&&P.J()&&(c=O.F(a))&&O.F("_cb_ls")){this.Hb=h;var d;switch(a){case "_SUPERFLY_lockout":d=600;break;case "_chartbeat4":d=60;break;case "_cb_cp":d=60;break;case "_chartbeat3":d=34128E3;break;default:d=34128E3}P.create(a,c,d)}return c};k.remove=function(a,b){a=b?a:this.Wa+a;(P.J()?P:O).remove(a);P.J()&&O.remove(a)};function gc(a){var b=i;if(a&&(b=hc()))return b;var c=m.location,b=Q(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),d=/&utm_[^=]+=[^&]+/ig;(c=d.exec(c.search))&&(a=a.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(c=d.exec(a))&&(a=a.replace(d,c[1]!=""?"?"+c[1]:""));return b+a}function hc(){var a=i;r(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=Bb(b.href),a=Q(b.pathname)+b.search+b.hash,j});return a}
for(var ic={},jc=0;jc<81;jc++)ic["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(jc)]=h;function kc(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return ic[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function Q(a){if(!y(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,kc);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function R(a,b){var c=S();return u(b)&&!u(c[a])?b:c[a]}function S(){u(m._cb_shared)||(m._cb_shared={});return m._cb_shared};function lc(a,b){Sb.call(this,a,b)}n(lc,Sb);lc.prototype.q=function(){this.ga=this.N=0;this.aa=i;this.Gb=E.M("x",this.Ea,this);this.Ea(I.Ic())};lc.prototype.Ea=function(a){Pa(this.aa);this.aa=i;if(a===I.tc.La)this.aa=Oa(this.Yb,1E3)};function T(){G.call(this);this.sa=[];this.D=new dc(this.mc);this.D.remove("_SUPERFLY_nosample");this.O=new Sb;this.pa=new lc;this.Bb=t(this.wa,this);w(m,"unload",this.Bb);wb(t(this.q,this))}n(T,G);k=T.prototype;k.Za=h;
k.q=function(){T.U.q.call(this);this.Ra=this.ha=0;this.ka=s();this.ya=p(mc(this));this.xa=h;this.wb=72E5;if(this.Za){var a=+this.k.sessionLength;if(!isNaN(a))this.wb=a*6E4}a=R("d");if(!a){var a=[],b=this.D.F("_chartbeat2",h);b.length>0&&(a=b.split("."));a.length>5&&(a=[]);var b=s(),c=this.D.F("_cb",h);c.length>0?a[1]=a[1]||b:c=a[0];a[0]="";var d=b-+(a[1]||0),e=b-+(a[2]||0);S().n=c&&d>18E5&&e<2592E6?0:1;d=a[4];if(!(e=e>18E5))if(nc(this))e=j;else{var e=U(this),e=decodeURIComponent(e),e=oc(e)||e,f;f=
pc(this);f=decodeURIComponent(f);f=oc(f)||f;e=e!==f}if(!d||e)d=p(mc(this)),a[4]=d,this.D.remove("_cb_svref",h);e="1";f=a&&+a[2];d=a&&a[3];if(a&&f&&d)if(e=Math.abs((Da(b)-Da(f))/864E5)){e=Math.min(e,16)-1;for(f="";e--;)f+=0;e=(d+f+"1").slice(-16)}else e=d;d=e;c||(c=this.k.utoken||p(mc(this),3),a[1]=b);a[2]=b;a[3]=d;this.k.utoken=this.na;this.D.create("_cb",c,34128E3,h);this.D.create("_chartbeat2",a.join("."),34128E3,h);a[0]=c;S().d=a}this.vd=a.join(".");var l;c=+a[1];d=+a[2];if((b=a[3])&&c&&d)l=(Math.min((Math.abs((Da(d)-
Da(c))/864E5)||0)+1,16,b.length)-1).toString(16),l+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.Wb=l;this.Vc=R("n",1);this.na=a[0];this.dd=a[4];this.cd=pc(this);this.D.create("_cb_svref",pc(this)||"null",1800,h);this.O.q();this.pa.q();I.q();F.q();kb||(lb=ub(),mb&&m.document.addEventListener&&m.document.addEventListener(mb,vb,j),tb("focus","onfocusin",rb),tb("blur","onfocusout",sb),lb&&rb(),kb=h);this.Ha=0;this.ib=E.M(jb,this.Ab,this)};
k.oa=function(){if(!this.D.F("_SUPERFLY_lockout")&&!pb)this.Uc?this.ab():(this.Uc=h,!m._sf_async_config&&!m._cbq?(this.Va=t(this.ab,this),w(m,"load",this.Va)):this.ab())};k.ab=function(){this.Cb=qc();F.q();var a=t(this.Ia,this);this.Zb=Oa(a,15E3);this.Ia()};
k.Ia=function(){var a=this.O.ga,a=this.k.reading&&+this.k.reading||a>0;if(this.Ra<this.ha&&!a)this.Ra++;else{var b;if(Ma===g)b=m.navigator.userAgent,Ma=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=Ma;b&&!a?this.Ra++:(a?this.ha=0:rc(this),this.Ra=0,this.sa.push(0),this.sa.length>18&&this.sa.shift(),this.Za&&s()-this.ka>=this.wb?this.terminate():this.ca())}};
function sc(a){var b={};b.g=a.k.uid;b.g0=Hb(a.k,"sections");b.g1=Hb(a.k,"authors");b.g2=Hb(a.k,"zone");b.g3=Hb(a.k,"sponsorName");b.g4=Hb(a.k,"type");!a.k.noCookies&&a.D.isSupported()?b.n=a.Vc:b.nc=1;b.c=Math.round((s()-a.ka)/600)/100;b.E=a.O.N;b.EE=a.pa.N;var c=tc(a);a.Ha=Math.max(a.Ha,c);b.x=c;b.m=a.Ha;b.y=Za("Height");b.o=Za("Width");b.w=Ya();b.b=a.Cb>0?a.Cb:"";if(a.Wb)b.f=a.Wb;b[""]=Ib(a.k);b.t=a.ya;b.V=90;b.tz=(new Date).getTimezoneOffset();b.sn=a.Db;b.sv=a.dd;b.sr=a.cd;return b}
k.hc=function(){this.sa.push(1);var a=0;r(this.sa,function(b){a+=b});a<3?(this.xa=h,rc(this)):(this.terminate(),this.D.create("_SUPERFLY_lockout","1",600))};k.wa=function(){};k.Ab=function(){var a=tc(this);this.Ha=Math.max(this.Ha,a)};function tc(a){return Math.floor(Wa("Y","Top",!!a.k.scrollElement))}function rc(a){var b=a.ha,b=b?Math.min(b*2,16):1;a.ha=b}k.ra=function(){this.wa();this.terminate()};k.bb=function(){this.q();this.oa()};
function nc(a){if(a.k.virtualReferrer)return h;if(uc(a))return j;a=document.referrer.indexOf("://"+m.location.hostname+"/");return a!=-1&&a<9}function uc(a){var b=a.k.referrerOverrideQueryParam,c="";r(window.location.search.substr(1).split("&"),function(a){a=a.split("=");if(a.length==2&&a[0]==b&&a[1])return c=decodeURIComponent(a[1]).replace(/\+/g," "),j});c&&c.indexOf("::")==-1&&(c="external::"+c);return c}
function U(a){a=a.k.virtualReferrer||uc(a);if(!a&&(a=document.referrer||"")&&!/^(android-)?app:/.test(a)){var b=Bb(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=Q(b.pathname),a=Cb(b)}return encodeURIComponent(a)}function vc(a){a=a.k.title.slice(0,100);return encodeURIComponent(a)}function mc(a){a=[U(a),Za("Width"),Za("Height")];return na(a)}
function wc(a){var b=[],c=a.D.F("_chartbeat4");c&&(r(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.D.remove("_chartbeat4"));return b}function pc(a){a=a.D.F("_cb_svref",h)||U(a)||"null";a==="null"&&(a="");return a}function oc(a){a=a.match(/^https?:\/\/([^\/]*)/);return!a?i:a[1]}function qc(){var a=m.performance&&m.performance.timing;if(!a||a.navigationStart==0)return-1;var b=a.navigationStart,a=a.loadEventStart;return Ca(b)&&b?Ca(a)&&a>b?a-b:s()-b:-1}
k.terminate=function(){this.O.terminate();this.pa.terminate();E.T(this.ib);this.Va!==g&&Ba("load",this.Va);Pa(this.Zb);S().d=g;S().n=g};k.ba=function(){this.terminate();Ba("unload",this.Bb);this.Bb=this.Va=this.D=this.sa=this.k=i;this.O.ba();this.O=i;this.pa.ba();this.pa=i;T.U.ba.call(this)};function V(){this.Eb=[];this.mc="_p_";this.Za=this.$b=j;w(m,"beforeunload",t(this.Yc,this));T.call(this)}n(V,T);
V.prototype.q=function(){V.U.q.call(this);var a=m.location;H(this.k,"pingServer","ping.chartbeat.net");H(this.k,"title",document.title);H(this.k,"domain",a.hostname);this.k.domain=oa(this.k.domain);H(this.k,"domainAd",this.k.domain);H(this.k,"path",gc(!!this.k.useCanonical));H(this.k,"engaged",j);this.ea=this.k[Eb]||"data-cb-ad-id";this.ta=this.bc=0;this.Hc=function(){var a=s()-this.bc;if(a<500){this.ta&&C(this.ta);var c=t(this.ca,this);this.ta=Qa(c,500-a)}else this.xa||this.ca()};this.Gc=E.M("p",
this.Hc,this);this.md=E.M("z",this.hd,this);if(this.k.krux&&!this.$b)ka("http://beacon.krzd.net/usermatch.gif?partner=chartbeat&partner_uid="+this.na),this.$b=h;this.Eb=[]};V.prototype.Yc=function(){xc(this);this.ca(h)};V.prototype.wa=function(){this.D.update("_chartbeat4",["t="+this.ya,"E="+this.O.N,"ad="+Ea(yc(this,h)),"x="+tc(this),"c="+Math.round((s()-this.ka)/600)/100,"y="+Za("Height"),"w="+Ya()].join("&"),60,g,g,1)};function zc(a){return encodeURIComponent("ads."+a.k.domainAd)}
function yc(a,b){var c=[];a.Aa&&r(a.Aa.X,function(a){a=$b(a);(!b||!(a.aw<=1&&a.ah<=1))&&c.push(Xb(a))});return c.concat(a.Eb).join("&")}var Ac="h,p,u,d,g,g0,g1,g2,g3,g4,n,nc,f,c,x,m,y,o,w,j,E,v,r,vp,b,t,V,i,tz,l,,ad,z,zz,sn".split(",");k=V.prototype;
k.ca=function(a){this.Db++;var b=sc(this),c=m.location;b.h=zc(this);b.p=encodeURIComponent(this.k.path);b.u=this.na;b.d=Ea(oa(c.hostname));nc(this)?b.v=U(this):b.r=U(this);b.ad=Ea(yc(this));this.bc=s();this.ta&&C(this.ta);gc(!!this.k.useCanonical);if(this.xa)this.xa=j,b.i=vc(this);this.k.virtualReferrer&&(b.vp=1);var c=this.k.pingServer,d=0;a?b.zz=1:(b.z=wc(this),d=Math.round((this.ha+2)*15E3/1E3));b.j=d;b.l=fc(this.D)?1:"";this.O.ga=0;this.Ka("https://"+c+"/ping/ad?"+Ab(b,Ac))};
k.Ab=function(){V.U.Ab.call(this);Bc(this.Aa)};k.Xa=function(a,b){a.H.Qb=b;var c=$b(a);this.Eb.push(Xb(c));a.refresh()};k.hd=function(a,b){for(var c=Ka(this.D.F("_chartbeat7")),d=parseInt(c[a.vzcid],10)||0,e={1:h,5:h,15:h,30:h,60:h,100:h};b--;)if(d++,e[d+""]){var f=a,l=d+"second"+(d!==1?"s":""),o=p(la());ka("http://ohlone.vizu.com/a.gif?vzcid="+f.vzcid+"&vzadid="+l+"&vzsid="+f.vzsid+"&ord="+o)}c[a.vzcid]=d;this.D.create("_chartbeat7",Ja(c),7862400)};
function xc(a){a.Aa&&r(a.Aa.X,function(a){if(a.H.Tb)a=a.H,ka("//secure.insightexpressai.com/adServer/cb.gif?bannerid="+a.G.dynamicLogic+"&siteID="+a.G.siteId+"&placementID="+a.G.placementId+"&creativeID="+a.G.creativeId+"&inViewTime="+a.Na.da.N+"&vendor=cb")})}k.terminate=function(){E.T(this.Gc);E.T(this.md);this.Qa&&E.T(this.Qa);C(this.ta);V.U.terminate.call(this)};function Cc(){this.X=[];this.k=m._sf_async_config||{};this.ea=this.k[Eb]||"data-cb-ad-id";"postMessage"in window&&w(window,"message",t(this.Rc,this));if(Db()>0){var a=t(this.Ma,this);S().a=a;var a="ad_debug",b="//static.chartbeat.com";eb()&&(b="//static2.chartbeat.com");b=[b,"js"];eb()&&(a+="dev");b.push("chartbeat_"+a+".js");db(b.join("/"))}this.Ya=[];wb(t(this.q,this))}k=Cc.prototype;
k.q=function(a){this.k=m._sf_async_config||{};a?this.B.q():(this.B=new V,this.B.Aa=this);this.Ba={};this.Ga=0;if((a=this.k.engagedAdFilters)&&a.length){var b=this;r(a,function(a){b.Oa(a)})}this.ma();this.Qa=E.M("e",this.Cc,this);try{m.googletag.pubads().addEventListener("slotRenderEnded",t(this.Nc,this))}catch(c){}};k.Nc=function(a){if(this.Ya.length)try{r(this.Ya,t(function(b,d){var e=b.pb;a.slot===e&&(e.setTargeting("_cbr",Dc),b.ob>=100||(b.ob+=1),this.Ya.splice(d,1))},this))}catch(b){}};
function Ec(){var a=Ua("id^=google_ads_iframe","div");return Ha(a,function(a){return a.parentNode})}function Fc(a){var b=j;r(a.X,function(a){if(a.Ta)return b=h,j});return b}k.Ma=function(a,b){var c=Ra(E,ib),d=Ra(I,Rb),e=t(function(){return{engagedAdFilters:this.Ba,maxEngagedAdSpecificity:this.Ga}},this);a.injectDependencies(c,d,e);b.injectDependencies(c);this.Sb=new a;Zb=b;r(this.X,function(a){a.Ma()})};
function Bc(a){var b=Ua(a.ea,"div");b.length||(b=Ec());b=Ua(a.B.ea,"div");r(b,function(b){if(!Gc(a,b)){var d=new J(b);d.H=new Tb;d.H.Na=d;a.X.push(d);d.ma();if(b=D("data-cb-engaged-seconds",b))d=cc(d),d[N]=parseInt(b,10),a.Oa(d)}})}function Gc(a,b){var c;r(a.X,function(a){if(a.qa===b||a.P===b)return c=a,j});return c}
k.ma=function(){var a=R("c"),b=this;Bc(b);r(b.X,function(c){c.ma();var d=c.qa;if(a&&a[d]){var e=-1;r(a[d],function(a,d){if(a.e===c.P)return a.c(b.B?b.B.ya:"1",b.B?zc(b.B):"1"),e=d,j});e>-1&&a[d].splice(e,1)}})};k.Rc=function(a){this.cc(y(a.data)?Ka(a.data):{},a.source)};
k.cc=function(a,b){if(a.cbType!=="campaignMessage")return j;var c=b;if(c.parent!=window){for(var d=0;c.parent!=window&&d<10;)c=c.parent,d++;if(d>=10)return j}Bc(this);var d=document.getElementsByTagName("iframe"),e=g;r(d,function(a){if(a.contentWindow===c)return e=a,j});if(!e)return j;var f,l,d=this.B?this.B.ea:"id^=google_ads_iframe";f=e.getAttribute(d);l=e;if(f===i){l=Va(e,d);if(!l)return j;f=l.getAttribute(d)}var o=g;r(this.X,function(a){if(f===a.qa&&l===a.P)return o=a,j});if(o===g)return j;o.$a(a,
e);if(d=a[N]){var q=cc(o);q[N]=parseInt(d,10);this.Oa(q)}d=["cbdata::ack",this.B?this.B.ya:"1",this.B?zc(this.B):"1"].join("::");"postMessage"in b&&b.postMessage(d,"*");return d};
k.Oa=function(a){if(a&&Ca(a[N])&&!isNaN(a[N])){var b={};r(bc,function(c){if(y(a[c])||c===N)b[c]=a[c]});var c=Sa(b).length;this.Ga=Math.max(this.Ga,c);this.Ba[c]=this.Ba[c]||[];var c=this.Ba[c],d=j;r(c,function(a){var c=h;r(a,function(a,d){if(d!==N)return c=b[d]===a});(d=c)&&(a[N]=b[N]);return!d});d||c.unshift(b);this.Sb&&this.Sb.update()}};k.oa=function(){this.B.oa()};
k.Zc=function(a,b){if(!a)return j;var c=m.document.getElementById(b);if(!c)return j;var d;c.getAttribute(this.B.ea)&&(d=Gc(this,c));var e=this;if(!d){var f=Ua(this.B.ea,"div",c);r(f,function(a){if(d=Gc(e,a))return j})}d||(c=Va(c,this.B.ea))&&(d=Gc(this,c));if(!d)return j;d.pb=a;return h};
k.Cc=function(a){if(a&&this.Ga!==0){var b=a.pb,c=this.k.engagedAdCallback;b&&!c&&(c=Na);if(c)for(var d=this,e=cc(a),f=e[N],l=this.Ga,o=j;l>0&&!o;)r(this.Ba[l]||[],function(l){o=h;r(l,function(a,b){if(b!==N)return o=a===e[b]});if(o){l=l[N];if(l===-1)return j;if(l===f)e.element=a.P,c(e,f),b&&a.yb==j&&(a.vb?Hc(d,a):Ic(d,a));return j}}),l--}};k.Xa=function(a){if(a&&(a=Gc(this,a)))this.B.Xa(a,1),a.H.kb=1};var Dc="0";
function Ic(a,b){a.B.Xa(b,2);var c=b.pb;try{c.setTargeting("_cbr",b.ob),a.Ya.push(b),m.googletag.pubads().refresh([c]),b.H.kb=2}catch(d){}}function Hc(a,b){(b.Ta||!Fc(a))&&r(a.X,function(b){b.vb&&Ic(a,b)})}Cc.prototype.ra=function(){this.B.wa();this.terminate()};Cc.prototype.bb=function(){this.q(h);this.B.oa()};Cc.prototype.terminate=function(){this.ib&&E.T(this.ib);this.B&&this.B.terminate();this.Qa&&E.T(this.Qa);r(this.X,function(a){a.terminate()});this.X=[];this.k=i};if(!m.pSUPERFLY_pub){var X=new Cc,Jc={addEngagedAdFilter:t(X.Oa,X),refreshAd:t(X.Xa,X),updateCampaignData:t(X.ma,X),registerGptSlot:t(X.Zc,X)};Jc.evps=t(X.ra,X);Jc.svps=t(X.bb,X);"postMessage"in window!==h&&(Jc.loadCampaign=t(X.cc,X));m.pSUPERFLY_pub=Jc;X.oa()};function Kc(a){for(var b=R("m")||[];b.length;)a(b.shift());a={push:a};S().m=a};function Lc(){var a=m.location.href,a=a.replace(/-{2,}/g,"-"),a=Bb(a);a.pathname=Q(a.pathname);return a}
function Mc(a){var b=O.F("_chartbeat6");if(!b)return i;var b=b.split("::"),c,d;if(b.length===1)c=b[0].split(","),d=0;else{var e,f=Lc(),l=Cb(f);r(b,function(a,b){var f=a.split(","),o=La(l,decodeURIComponent(f[0]));if(o===0)return c=f,d=b,j;if(e===g||o<e)e=o,c=f,d=b})}b.splice(d,1);a="_chartbeat6="+b.join("::")+Nc(a);document.cookie=a;var a=[],b=decodeURIComponent(c[0]),f=decodeURIComponent(c[1]),o=c[2];c.splice(0,3);for(var q=c.length/2,v=0;v<q;v++)a.push({td:b,origin:f,va:o,Dc:c[v*2],jd:c[v*2+1]});
return a}function Nc(a){var b="",c;if(!B(a))return b;a.fc&&(c=new Date,c.setTime(c.getTime()+a.fc),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function Oc(a){var b=a.topStorageDomain,a=a.domain,c=m.location.hostname;return b?b:Pc(c,a)?a:c.replace(/^www\./,"")}function Pc(a,b){if(a===b)return h;for(var c=b.split("."),d=a.split(".");c.length;){if(d.length===0)return j;if(c.pop()!==d.pop())return j}return h}
function Qc(a,b,c,d){this.Fc=a;this.Ec=b;this.kd=c;this.va=d};function Rc(a,b){for(var c=b||document.documentElement,d=[],e=i,f=a,l,o,q,v,z,L;f&&f!==c;){l=f.nodeName.toLowerCase();e=f;o=e.nodeName;if((f=f.parentNode)&&f!==document.documentElement){q=f.children;v=0;for(z=0,L=q.length;z<L;z++){if(e===q[z]){l+="["+(1+z-v)+"]";break}q[z].nodeName!==o&&v++}}d.unshift(l)}return d.join("/")};function Sc(){this.mc="_t_";T.call(this)}n(Sc,T);k=Sc.prototype;
k.q=function(){Sc.U.q.call(this);Gb(this.k);var a=m.location;H(this.k,"mabServer","mabping.chartbeat.net");H(this.k,"title",document.title);H(this.k,"domain",a.hostname);H(this.k,"path",gc(!!this.k.useCanonical));this.Fa=oa(a.hostname);this.k.domain=oa(this.k.domain);this.fd=Oc(this.k);this.Ca=this.Sa=j;this.Vb=[];var b=this,a=Mc({domain:"."+this.fd,fc:6E4,path:"/"});if(a!==i)this.Sa=h,r(a,function(a){b.Vb.push(new Qc(a.origin,a.Dc,a.jd,a.va))});this.gc=0;this.cb=i;Kc(t(this.Sc,this))};
k.ca=function(){var a=this.O.N,b=Tc(this),c,d=this;this.Sa&&r(this.Vb,function(e){c=b+"&x="+e.Ec+"&v="+e.kd+"&ml="+e.va+"&xo="+e.Fc+"&e="+a;d.Ka(c)});!this.Ca&&this.cb&&Uc(this,this.cb);this.Ca=h};k.ab=function(){this.Cb=qc();F.q();if(this.Sa){var a=t(this.Ia,this);this.Zb=Oa(a,500)}this.Ia()};k.Ia=function(){var a,b;this.Ca?(a=this.O.N,b=this.gc*15,a-b>=15&&(this.ca(),this.gc+=1),a>=45&&this.terminate()):this.ca()};
function Tc(a){var b=a.k;return Fa()+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&d="+encodeURIComponent(a.Fa)+"&u="+a.na+"&c="+Math.round((s()-a.ka)/600)/100}k.wa=function(){};k.ed=function(a){var b=a.d,c=i;b!==i&&(c={kc:b.s,va:b.g,ec:b.m});a={status:a.s,data:c,code:a.c,message:a.m};this.Ca?Uc(this,a):this.cb=a};
function Uc(a,b){var c=Tc(a),d=b.status,e=b.data;if(d=="s"&&e!==i){var f=t(a.Ka,a);B(e.kc)&&r(e.kc,function(a,b){f(c+"&x="+b+"&v="+a+"&ml="+e.va+"&e=-1")});Object.prototype.toString.call(e.ec)==="[object Array]"&&r(e.ec,function(a){f(c+"&me=3&ml="+e.va+"&x="+a)})}else d=="e"&&a.Ka(c+"&me="+b.code)}k.Sc=function(a,b){for(var c=0,d=arguments.length;c<d;c++){var a=arguments[c],e=a.shift();e==="t"?this.ed.apply(this,a):e==="v"&&this.bd.apply(this,a)}};k.ra=function(){S().m=[];u(this.Kb)&&this.Kb();Sc.U.ra.call(this)};
k.bd=function(a){this.Kb=a};k.terminate=function(){this.Kb=this.ud=g;this.cb=i;this.Ca=this.Sa=g;Sc.U.terminate.call(this)};if(!m.pSUPERFLY_mab){var Vc=new Sc,Xc={};Xc.evps=t(Vc.ra,Vc);Xc.svps=t(Vc.bb,Vc);m.pSUPERFLY_mab=Xc;Vc.oa()};var Yc,Zc,$c;function ad(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0&&(a=a.substr(16),bd(),a!=="NONE"))){var a=a.indexOf("HUD2.")===0?a.substr(5):"OLD",b="https://static.chartbeat.com/js/inpage.js";a!=="OLD"&&(b="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+a+".js");db(b)}}function bd(){C(Zc);Zc=g;Ba("message",ad);$c&&$c.parentNode&&$c.parentNode.removeChild($c);$c=g};function cd(){var a=m._sf_async_config&&m._sf_async_config.domain;if(a&&!Yc){Yc=h;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);w(m,"message",ad);Zc=Qa(bd,1E4);var b=u(g)?g:{};b.src=a;a=cb("iframe",b);a.style.display="none";u(g)?g.appendChild(a):document.body&&document.body.appendChild(a);$c=a}}
function dd(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=P.J(h),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),cd(),Ba("message",dd))}};function Y(){"postMessage"in window&&w(m,"message",t(this.Qc,this));T.call(this);Fb("_cbq",t(this.ic,this))}n(Y,T);
Y.prototype.q=function(){Y.U.q.call(this);var a=this.na;S().u=a;a=this.ya;S().t=a;this.jb=i;Gb(this.k);a=m.location;H(this.k,"pingServer","ping.chartbeat.net");H(this.k,"title",document.title);H(this.k,"domain",a.hostname);this.k.path=this.k.path?Q(this.k.path):gc(!!this.k.useCanonical);this.Fa=oa(a.hostname);this.k.domain=oa(this.k.domain);this.wc=E.M("c",this.Wc,this);this.xc=E.M("r",this.Xc,this);this.ua=i};Y.prototype.uc=function(a){this.jb=a};
Y.prototype.wa=function(){this.D.update("_chartbeat4",["t="+this.ya,"E="+this.O.N,"EE="+this.pa.N,"x="+tc(this),"c="+Math.round((s()-this.ka)/600)/100,"y="+Za("Height"),"w="+Ya()].join("&"),60,g,g,1)};var ed="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,_s,t,V,z,i,L,tz,l,,sn,C,eS,eM,eD,eK,eR,EE,sv,sr".split(",");k=Y.prototype;
k.ca=function(a){this.Db++;var b=sc(this),c=this.O.ga;b.h=encodeURIComponent(this.k.domain);b.p=encodeURIComponent(this.k.path);b.u=this.na;b.d=encodeURIComponent(this.Fa);b.j=Math.round((this.ha+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;var d=b.c*6E4+this.ka;b.eD=F.Da("mousedown",d);b.eM=F.Da("mousemove",d);b.eK=F.Da("keydown",d);b.eR=F.Da("resize",d);b.eS=F.Da("scroll",d);F.$c();F.vc()?b.W=1:this.k.reading&&+this.k.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=nc(this);if(this.xa){this.xa=j;if(c)this.ua=fd(this);
b.i=vc(this);d=this.k.hudTrackable;d!==g&&(b.L=d?"1":"0");this.k.alias&&(b.PA=encodeURIComponent(this.k.alias))}if(c){if(this.ua){if(b.v=encodeURIComponent(this.ua.path),b.K=gd(this.ua),this.ua.zb>1)b.l1=this.ua.zb}else b.v=U(this);this.k.virtualReferrer&&(b.vp=1)}else b.r=U(this);c=Ta(b.v);S().v=c;c=Ta(b.r);S().r=c;b.A=this.jb?this.jb:"";b._c=yb("utm_campaign",this.k.campaignTag);b._m=yb("utm_medium",this.k.mediumTag);this.k.idSync?(c=[],ca(new ba,this.k.idSync,c),c=encodeURIComponent(c.join(""))):
c="";b._s=c;b.z=wc(this);b.C=this.k.mobileApp?1:"";b.KK=a?gd(a):"";b.l=fc(this.D)?1:"";this.O.ga=0;this.Ka(Fa()+"//"+this.k.pingServer+"/ping?"+Ab(b,ed))};
k.Qc=function(a){var b=this.k,c=b.playerdomain||this.Fa;if(qa(a.origin)===qa(c))if(c=a.data,y(c)&&c.indexOf("cbqpush::")===0)a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.ic(a));else if(c=="cbdata?"){var c="&u="+R("u"),d="&t="+R("t"),e="&v="+R("v"),f="&r="+R("r"),b="domain="+encodeURIComponent(b.domain)+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b.path)+"&title="+vc(this)+"&referrer="+U(this)+"&internal="+(nc(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.Fa)+
c+d+e+f+"&utoken="+this.na;a.source.postMessage(b,"*")}};k.ic=function(a){a[0]==="_demo"&&this.k._demo?this.k._demo=this.k._demo+"%2C"+a[1]:this.k[a[0]]=a[1];this.ha=0};function hd(a){a=a.replace(/-{2,}/g,"-");a=Bb(a);a.pathname=Q(a.pathname);return a}k.Wc=function(a){id(this,a,"c")};k.Xc=function(a){id(this,a,"r")};
function id(a,b,c){if(a.Za&&s()-a.ka>=a.wb)a.terminate();else{var d=b.href||"",d=hd(d);if(d.protocol.indexOf("http")===0){var e=d.hostname!==m.location.hostname,d=Cb(d),f=$a(b,function(a){return a.id}),l=Rc(b,f),o="";a.k.moduleAttribute&&(o=(o=Va(b,a.k.moduleAttribute))?o.getAttribute(a.k.moduleAttribute):"",o=o.replace(/::/g,"-").substr(0,40));f?(l&&(l="/"+l),l="*[@id='"+f.id+"']"+l,f=Rc(b)):f=l;l=p(l);f=p(f);b=Ob(b,g,h);c={left:b.x,top:b.y,path:a.k.path,href:d,Nb:l,hb:f,Mb:"",Fb:c,zb:0,Jc:a.k.domain,
xb:o};a.ca(c);e||a.D.update("_chartbeat5",jd(c),60,j,g,3,function(a){a=a.split(",");return a[2]+","+a[3]})}}}function gd(a){return[a.left,a.top,a.Nb,encodeURIComponent(a.Mb),a.Fb,encodeURIComponent(a.href),a.hb,a.xb].join("::")}function jd(a){var b=encodeURIComponent(a.Mb),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.Nb,b,a.Fb,a.hb,encodeURIComponent(a.Jc),a.xb].join(",")}
function fd(a){var b=a.D.F("_chartbeat5");if(!b)return i;var c=b.split("::"),b=c.length,d,e=i,f,l=hd(m.location.href),o=Cb(l);r(c,function(a,b){var c=a.split(","),l=Aa(o,decodeURIComponent(c[3]));if(l===0)return d=c,e=b,j;else if(l===i)return h;if(f===g||l<f)f=l,d=c,e=b});if(e===i)return i;c.splice(e,1);a.D.create("_chartbeat5",c.join("::"),60);(a=d[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),href:decodeURIComponent(d[3]),Nb:d[4]||
"",Mb:"",hb:d.length>7?d[7]:"",Fb:d.length>6?d[6]:"c",zb:b,xb:d[9]?d[9]:""}}k.terminate=function(){E.T(this.wc);E.T(this.xc);Y.U.terminate.call(this)};if(!m.pSUPERFLY){var kd=new Y,ld={};m.pSUPERFLY=ld;var md=m.pSUPERFLY_mab,Z=m.pSUPERFLY_pub,nd=[];md&&nd.push(md);if(Z)nd.push(Z),Z.addEngagedAdFilter&&(ld.addEngagedAdFilter=Z.addEngagedAdFilter),Z.refreshAd&&(ld.refreshAd=Z.refreshAd),Z.registerGptSlot&&(ld.registerGptSlot=Z.registerGptSlot),Fb("_cba",function(a){a()});ld.virtualPage=function(a,b){if(!pb){var c=m._sf_async_config;c.virtualReferrer=Fa()+"//"+c.domain+c.path;c.path=Q(a);b&&(c.title=b);kd.ra();r(nd,function(a){a.evps()});kd.bb();r(nd,
function(a){a.svps()})}};ld.activity=t(kd.uc,kd);kd.oa();var od=P.J(h);if(od)if(od.getItem("_cb_ip")){var pd=m.location;(!/^(.+[.])?chartbeat\.com$/.test(pd.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(pd.pathname))||cd()}else w(m,"message",dd)};})();
