(function() { //Sonobi - Morpheus version:3.10.1
'use strict';var w="function"==typeof Object.defineProperties?Object.defineProperty:function(g,d,m){if(m.get||m.set)throw new TypeError("ES3 does not support getters and setters.");g!=Array.prototype&&g!=Object.prototype&&(g[d]=m.value)},x="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function G(){G=function(){};x.Symbol||(x.Symbol=ma)}var na=0;function ma(g){return"jscomp_symbol_"+(g||"")+na++}
function H(){G();var g=x.Symbol.iterator;g||(g=x.Symbol.iterator=x.Symbol("iterator"));"function"!=typeof Array.prototype[g]&&w(Array.prototype,g,{configurable:!0,writable:!0,value:function(){return N(this)}});H=function(){}}function N(g){var d=0;return oa(function(){return d<g.length?{done:!1,value:g[d++]}:{done:!0}})}function oa(g){H();g={next:g};g[x.Symbol.iterator]=function(){return this};return g}function T(g){H();G();H();var d=g[Symbol.iterator];return d?d.call(g):N(g)}
function pa(g,d){function m(){}m.prototype=d.prototype;g.prototype=new m;g.prototype.constructor=g;for(var l in d)if(Object.defineProperties){var n=Object.getOwnPropertyDescriptor(d,l);n&&Object.defineProperty(g,l,n)}else g[l]=d[l]}function U(g,d){if(d){var m=x;g=g.split(".");for(var l=0;l<g.length-1;l++){var n=g[l];n in m||(m[n]={});m=m[n]}g=g[g.length-1];l=m[g];d=d(l);d!=l&&null!=d&&w(m,g,{configurable:!0,writable:!0,value:d})}}U("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});
U("Array.from",function(g){return g?g:function(d,g,l){H();g=g?g:function(f){return f};var n=[],f=d[Symbol.iterator];if("function"==typeof f)for(d=f.call(d);!(f=d.next()).done;)n.push(g.call(l,f.value));else for(var f=d.length,r=0;r<f;r++)n.push(g.call(l,d[r]));return n}});
U("Promise",function(g){function d(f){this.b=0;this.j=void 0;this.a=[];var d=this.h();try{f(d.resolve,d.reject)}catch(C){d.reject(C)}}function m(){this.a=null}if(g)return g;m.prototype.b=function(f){this.a||(this.a=[],this.h());this.a.push(f)};m.prototype.h=function(){var f=this;this.f(function(){f.j()})};var l=x.setTimeout;m.prototype.f=function(f){l(f,0)};m.prototype.j=function(){for(;this.a&&this.a.length;){var f=this.a;this.a=[];for(var d=0;d<f.length;++d){var g=f[d];delete f[d];try{g()}catch(D){this.i(D)}}}this.a=
null};m.prototype.i=function(f){this.f(function(){throw f;})};d.prototype.h=function(){function f(f){return function(r){g||(g=!0,f.call(d,r))}}var d=this,g=!1;return{resolve:f(this.Ja),reject:f(this.i)}};d.prototype.Ja=function(f){if(f===this)this.i(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof d)this.Ka(f);else{var g;a:switch(typeof f){case "object":g=null!=f;break a;case "function":g=!0;break a;default:g=!1}g?this.Da(f):this.v(f)}};d.prototype.Da=function(f){var d=void 0;
try{d=f.then}catch(C){this.i(C);return}"function"==typeof d?this.gb(d,f):this.v(f)};d.prototype.i=function(f){this.G(2,f)};d.prototype.v=function(f){this.G(1,f)};d.prototype.G=function(f,d){if(0!=this.b)throw Error("Cannot settle("+f+", "+d|"): Promise already settled in state"+this.b);this.b=f;this.j=d;this.Ca()};d.prototype.Ca=function(){if(this.a){for(var f=this.a,d=0;d<f.length;++d)f[d].call(),f[d]=null;this.a=null}};var n=new m;d.prototype.Ka=function(d){var f=this.h();d.f(f.resolve,f.reject)};
d.prototype.gb=function(d,g){var f=this.h();try{d.call(g,f.resolve,f.reject)}catch(D){f.reject(D)}};d.prototype.then=function(f,g){function l(d,f){return"function"==typeof d?function(f){try{n(d(f))}catch(y){m(y)}}:f}var n,m,r=new d(function(d,f){n=d;m=f});this.f(l(f,n),l(g,m));return r};d.prototype.catch=function(d){return this.then(void 0,d)};d.prototype.f=function(d,g){function f(){switch(l.b){case 1:d(l.j);break;case 2:g(l.j);break;default:throw Error("Unexpected state: "+l.b);}}var l=this;this.a?
this.a.push(function(){n.b(f)}):n.b(f)};d.resolve=function(f){return f instanceof d?f:new d(function(d){d(f)})};d.reject=function(f){return new d(function(d,g){g(f)})};d.b=function(f){return new d(function(g,l){for(var n=T(f),m=n.next();!m.done;m=n.next())d.resolve(m.value).f(g,l)})};d.a=function(f){var g=T(f),l=g.next();return l.done?d.resolve([]):new d(function(f,m){function n(d){return function(g){r[d]=g;B--;B||f(r)}}var r=[],B=0;do r.push(void 0),B++,d.resolve(l.value).f(n(r.length-1),m),l=g.next();
while(!l.done)})};d.$jscomp$new$AsyncExecutor=function(){return new m};return d});U("Object.assign",function(g){return g?g:function(d,g){for(var l=1;l<arguments.length;l++){var n=arguments[l];if(n)for(var f in n)Object.prototype.hasOwnProperty.call(n,f)&&(d[f]=n[f])}return d}});U("Array.prototype.find",function(g){return g?g:function(d,g){a:{var l=this;l instanceof String&&(l=String(l));for(var n=l.length,f=0;f<n;f++){var m=l[f];if(d.call(g,m,f,l)){d=m;break a}}d=void 0}return d}});
(function(g){function d(){var a=Object.assign(h.sbi_morpheus||{},{registration:{},register:function(){},enableReactiveSizes:function(){},callOperator:function(){},initialized:!1,initialize:function(){for(var b=a.cmd;0<b.length;)try{b.shift()()}catch(c){}a.initialized=!0},cmd:function(){var a=[],c=a.push;a.push=function(b){for(var e=[],p=0;p<arguments.length;++p)e[p-0]=arguments[p];return h.sbi_morpheus.initialized?e.reduce(function(a,b){try{b()}catch(E){}a++;return a},0):c.apply(a,e)};return a}()});
return a}function m(a){this.ib=new l(a);this.P=new K(a);this.H=new B(a)}function l(a){this.a=a.analyticsSettings;this.P=new K(a)}function n(a,b){this.c=a;this.b=b;this.caller=new F;this.a=[]}function f(a,b){this.c=a;this.b={};this.K=b;this.a={}}function r(a,b){var c=a.$({name:b});if(c)return{Fa:c,exec:function(a){return q.za(h,a.value)}};if(c=a.$({name:""+b+"_cookie_key"}))return{Fa:c,exec:function(a){return q.Ua(a.value)}}}function C(a){return{Fa:{name:"vp"},exec:function(){return(q.ia(a.H.Z())||
"desktop").toLowerCase()}}}function D(a){var b=["hfa","cdf","ant"].map(function(b){return r(a,b)}).filter(function(a){return a});b.push(C(a));return b.reduce(function(a,b){var c=b.Fa;b=b.exec;var e="";"function"===typeof b&&(e=b(c));if(!e)return a;if("object"===typeof e||Array.isArray(e))e=JSON.stringify(e);return a+"&"+c.name.replace("_cookie_key","")+"="+encodeURIComponent(e)},"")}function J(a,b,c,e,k,p,L){this.da=q.Sa();this.j=e;this.R=k;this.V=0;this.S=c;this.ea=b;this.b="";this.X=a;this.i={};
this.na="";this.f=10;this.a=-1;this.W=1;this.h={};this.U=L;this.T=0;this.v="display";"function"===typeof p.O&&p.O(this.ha(1))}function V(a){this.name=a.name;this.pa=a.pa;this.Ga=a.Ga;this.request=a.request;this.parse=a.parse;this.done=Function;this.caller=new F;this.L={};this.c={};this.b=Promise.resolve({});this.a=!1}function A(a,b){if(!b)throw Error("Provide an adapter name in your AdapterSettingsConfigInterface constructor.");this.f=a.adapterSettings;this.H=new B(a);a=this.f;for(var c={},e=0;e<
a.length;e++)c[a[e].name]=a[e];this.b=c;this.m=b;this.a=this.b[b];this.G=X;this.v=Y}function B(a){this.a=a.platformSettings;this.P=new K(a)}function K(a){this.a=a.globalSettings}function y(a,b,c,e){this.c=a;this.qa=b;this.a={};this.f=c;this.K=e;var k=this;this.ya=function(a){if("object"!==typeof a)return k.a;a.aa=!1;return Object.keys(k.a).reduce(function(b,c){var e=k.a[c],p;for(p in a)if(e[p]!==a[p])return b;b[c]=e;return b},{})};this.ga=function(a){if("object"===typeof a)return a.aa=!1,k.a[Object.keys(k.a).find(function(b){b=
k.a[b];for(var c in a)if(b[c]!==a[c])return!1;return!0})]};this.j=function(){};this.b=new t(this.c,this);h.sbi_km.API.render=function(){var a=arguments,b=Date.now(),e=Object.assign({},c.fa),d=e[Object.keys(e).find(function(b){b=e[b];return b.id===a[1]&&!b.ba})];if(d){var f=k.a[d.o];f&&(f.Xa[d.id]=b,k.b.Da(f,arguments[0],d.Y,arguments[2],arguments[3]).then(function(a){if(null==a)throw"Slot didn't exist when render was called";a=k.i([a]);if(null==a)throw"Could not find slot for some reason";a=a[Object.keys(a)[0]];
var b=Object.keys(a.Xa),b=k.f.fa[b[0]];k.c.log("sbi",200019,[b.g,b.B]);b.response=6;b.ba=!0;k.K.O(b.ha(3));a.fb={}}).catch(function(a){k.c.log("sbi",200040,[a])}))}};this.b.once("initialized",function(a,b){k.c.log("sbi",200003,[a]);k.h(a);"function"===typeof b&&b();k.b.A("slotsDefined",function(a){k.c.log("sbi",200027,[a]);k.h(a)})});this.b.A("slotsDestroyed",function(a){a.forEach(function(a){var b=k.b.h(a);a=k.b.G(a);for(var c in k.a)k.a[c].w===b&&k.a[c].o===a&&(k.a[c].aa=!0,k.c.log("sbi",200028,
[k.a[c]]))},this)});this.b.A("getSlots",function(a,b){"object"!==typeof a?b(k.a):(a.aa=!1,b(Object.keys(k.a).reduce(function(b,c){var e=k.a[c],p;for(p in a)if(e[p]!==a[p])return b;b[c]=e;return b},{})))});this.b.A("findSlot",function(a,b){"object"!==typeof a?b({}):(a.aa=!1,b(k.a[Object.keys(k.a).find(function(b){b=k.a[b];for(var c in a)if(b[c]!==a[c])return!1;return!0})]))});this.b.A("slotsRequestingRender",function(a){var b=k.i(a.C);k.j(b,a.done)});this.b.A("newPageViewRequested",function(){k.b.Ka()});
this.b.A("log",function(a){k.c.log.apply(k.c,Array.isArray(a)?a:[a])})}function t(a,b){var c;this.a={};c=this;c.F=!1;c.ra=Function;c.sa=Function;c.Ta={};c.l={};c.c=a;c.la=[];c.ya=b.ya;c.ga=b.ga;h.googletag=h.googletag||{};h.googletag.cmd=h.googletag.cmd||[];if(h.googletag.pubadsReady)a.log("sbi",200039);else{a=null!=h.googletag.cmd.length?"unshift":"push";var e=!1,k=function(){e||(e=!0,c.Ta=h.googletag,c.l=c.Ta.pubads(),c.vb(),c.Bb())};h.googletag.cmd[a](k);if(!1!==O(b.qa,"globalSettings.osEnabled")&&
"u"===a[0]){var d=h.googletag.cmd.splice;h.googletag.cmd[a]=function(a){d.apply(h.googletag.cmd,[1,0,a]);return this.length};h.googletag.cmd.splice=function(){var a=d.apply(h.googletag.cmd,arguments);d.apply(h.googletag.cmd,[0,0,k]);return a}}c.ca={Xb:!1,Na:!1,Oa:!1,lb:!1};c.oa={}}return c}function M(){this.a={}}function I(a){this.caller=new F;this.qa=a;this.a=!1;this.navigationStart=h.performance.timing.navigationStart}function F(a){this.timeout=void 0===a?3E4:a}function P(a){var b=!1;return function(c){for(var e=
[],k=0;k<arguments.length;++k)e[k-0]=arguments[k];if(!b){b=!0;try{a.apply(a,e)}catch(p){}}}}function aa(a){a=void 0===a?[]:a;if(!Array.isArray(a))return[];a=Array.from(a);for(var b=a.length;b;b--){var c=Math.floor(Math.random()*b),e=T([a[c],a[b-1]]);a[b-1]=e.next().value;a[c]=e.next().value}return a}function qa(a){return parseInt(a,10)}function O(a,b){var c;if(b&&"string"===typeof b){if(-1!==b.indexOf(".")){b=b.split(".");for(var e=!1,k=0;k<b.length;k++){if("object"!==typeof a){e=!0;break}a=O(a,b[k])}e||
(c=a);return c}e="get"+b[0].toUpperCase()+b.slice(1);b=a&&"function"===typeof a[e]?e:b;a&&(a.hasOwnProperty(b)||"function"===typeof a[b])&&(c="function"===typeof a[b]?a[b]():a[b]);return c}}function ba(a){return a?'<script type="text/javascript" src="'+a+'">\x3c/script>':""}function ca(a,b){if(!a)return"";b=b.split("x");return'<iframe id="'+z()+'" width="'+b[0]+'" height="'+b[1]+'" marginwidth="0" marginheight="0" style="border:0" frameborder="0" src="'+a+'" border="0" scrolling="no" vspace="0" hspace="0"></iframe>'}
function da(a){return a?'<div style="position:absolute;left:0px;top:0px;visibility:hidden;">'+('<img src="'+a+'"></div>'):""}function ea(a,b){var c=[];a.forEach(function(a){-1!==b.indexOf(a)&&c.push(a)});return c}function fa(){return[h.innerWidth||h.document.documentElement.clientWidth||h.document.body.clientWidth,h.innerHeight||h.document.documentElement.clientHeight||h.document.body.clientHeight]}function ga(a,b){a=Math.round(a);for(var c=0;c<b.length;c++){var e="lt"in b[c]&&a<b[c].lt||!("lt"in
b[c]);!("ge"in b[c]&&a>=b[c].ge)&&"ge"in b[c]||!e||("set"in b[c]?a=b[c].set:"round"in b[c]&&(a=Math.floor(a)-Math.floor(a)%b[c].round))}return a}function ha(a,b,c){Object.keys(b).forEach(function(e){a=a.replace(c+e+c,b[e])});return a}function z(){return ra()+Math.random().toString(16).substr(2)}function sa(a){return a?a.replace(/^\?/,"").split("&").reduce(function(a,c){var b=T(c.split("="));c=b.next().value;b=b.next().value;/\[\]$/.test(c)?(c=c.replace("[]",""),a[c]=a[c]||[],a[c].push(b)):a[c]=b||
"";return a},{}):{}}function ta(a){return Object.keys(a).map(function(b){return Array.isArray(a[b])?a[b].map(function(a){return b+"[]="+a}).join("&"):b+"="+a[b]}).join("&")}function ua(a){var b=h.document.createElement("a");b.href=decodeURIComponent(a);return{protocol:(b.protocol||"").replace(/:$/,""),hostname:b.hostname,port:+b.port,pathname:b.pathname,search:sa(b.search||""),hash:(b.hash||"").replace(/^#/,""),host:b.host}}function va(a){return(a.protocol||"http")+"://"+(a.host||a.hostname+(a.port?
":"+a.port:""))+(a.pathname||"")+(a.search?"?"+ta(a.search||""):"")+(a.hash?"#"+a.hash:"")}function X(a,b,c){a=q.za(a,void 0===c?"dimensions.platforms":c)||[];return"*"===b||0===a.length||-1<a.indexOf("*")?!0:-1<a.indexOf(b)}function Y(a,b){var c=h.location.href;a=q.za(a,void 0===b?"dimensions.domains":b)||[];if(0===a.length||-1<a.indexOf("*"))return!0;if("string"===typeof a)return(new RegExp(a)).test(c);for(b=0;b<a.length;b++)if((new RegExp(a[b])).test(c))return!0;return!1}function wa(a,b,c,e,k,
d){function p(){l=z();u[l]={count:0,Pa:0,Ya:[],eb:[],bb:[],Wa:!0};setTimeout(function(){u[l].bb.forEach(function(a){return a()});u[l].Wa=!1},b.globalSettings.renderQueue)}function f(a){l&&u[l].Wa||p();u[l].bb.push(a);u[l].count++}function g(a,b){var c=u[a].Ya.push(b)-1;return function(b){u[a].Pa++;u[a].eb[c]=b;u[a].Pa===u[a].count&&Z(a)}}function Z(a){u[a].Ya.forEach(function(b,c){b(u[a].eb[c])})}var u={},l;return{yb:function(p,E){h.sbi_morpheus.initialized||h.sbi_morpheus.initialize();if(Object.keys(p).length){var L=
z(),W=P(function(b){var c=Object.keys(b).map(function(a){return b[a]});c.length?(e.Ab(a.pb(c,k.P.ja("priceRules")||[])),c=c.map(function(a){return a.clone()}),c.length&&(c=c.map(function(a){a.o=p[a.o].o;return a}),d.M(c),E())):E()});0<b.globalSettings.renderQueue?f(function(){return a.$a(p,b,c,L,g(l,W))}):a.$a(p,b,c,L,W)}},Yb:p,Mb:f,Rb:g,fc:Z,hc:u,gc:l}}var h=window;(function(){(function(a){"performance"in a||(a.performance={});Date.now=Date.now||function(){return(new Date).getTime()};if(!("now"in
a.performance)){var b=Date.now();a.performance.timing&&a.performance.timing.navigationStart?b=a.performance.timing.navigationStart:a.performance.timing={navigationStart:Date.now()};a.performance.now=function(){return Date.now()-b}}})(h);Object.assign||Object.defineProperty(Object,"assign",{enumerable:!1,configurable:!0,writable:!0,value:function(a){if(void 0===a||null===a)throw new TypeError("Cannot convert first argument to object");for(var b=Object(a),c=1;c<arguments.length;c++){var e=arguments[c];
if(void 0!==e&&null!==e)for(var k=Object.keys(Object(e)),d=0,f=k.length;d<f;d++){var g=k[d],h=Object.getOwnPropertyDescriptor(e,g);h&&h.enumerable&&(b[g]=e[g])}}return b}})})();var ra=function(){var a=0;return function(){a++;return a}}(),ia={highestCPMWins:function(a,b){if(0===a.length)return null;for(var c={g:0},e=0;e<a.length;e++)c.g>=a[e].g?b.log("sbi",200017,[a[e].g,a[e].B]):c=a[e];return c.g?c:null},sonobiDealWinsOverHighestCPM:function(a,b){if(0===a.length)return null;for(var c={g:0},e=0;e<
a.length;e++)if(10<=a[e].N)a[e].g>c.g&&(b.log("sbi",200017,[c.g,c.B]),c=a[e]);else{if("sonobi"===a[e].B&&a[e].I){c=a[e];a.forEach(function(k){k!==c&&b.log("sbi",200017,[a[e].g,a[e].B])});break}c.g>=a[e].g?b.log("sbi",200017,[a[e].g,a[e].B]):c=a[e]}return c.g||c.I?c:null},lowestDealPriorityWinsOverHighestCPM:function(a,b){if(0===a.length)return null;a.sort(function(a,b){return a.N-b.N});var c=a[0].N,e=a.filter(function(a){return a.N===c});a={g:0};for(var e=T(e),k=e.next();!k.done;k=e.next())k=k.value,
a.g>=k.g?b.log("sbi",200017,[k.g,k.B]):a=k;return a.g||a.I?a:null}},q={Sa:z,Nb:function(a){var b=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;return b.test(a)?a.replace(b,function(a){var b={"\b":"\\b"," ":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"}[a];return("string"==typeof b?b:"\\u")+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}):a},Ub:function(a){if(a){var b;try{b=a.contentWindow?a.contentWindow.document:
a.contentDocument.document?a.contentDocument.document:a.contentDocument}catch(c){return}return b}},Tb:function(){var a=h.document.createElement("iframe");a.id=z();a.height=0;a.width=0;a.hspace="0";a.vspace="0";a.marginWidth="0";a.marginHeight="0";a.style.border="0";a.frameBorder="0";a.border="0px";a.scrolling="no";a.src="about:blank";a.style.display="none";return a},ic:ha,$b:function(){return"Worker"in h&&"Blob"in h},cc:function(a,b){for(var c=0,e=a.length>b.length?b.length:a.length,k=a.length<b.length?
b.length:a.length,d=0;d<e;d++)a[d]===b[d]&&c++;return c/k},Db:ia,Eb:ga,Vb:fa,Ob:ea,Sb:function(a){return Object.keys(a).map(function(b){return Array.isArray(a[b])?a[b].map(function(a){return b+"[]="+a}).join("&"):b+"="+a[b]}).join("&")},nb:function(a){try{var b=new RegExp(a,"i"),c=h.performance.getEntriesByType("resource").filter(function(a){return b.test(a.name)});return Array.isArray(c)?Math.max(c[c.length-1].duration||0,0):null}catch(e){return null}},Ba:function(a){return void 0!=={sizes:1,ec:1,
timeout:1}[a]},ia:function(a){var b=h.innerWidth,c;for(c in a)if(a.hasOwnProperty(c)){var e=a[c].viewport.lt||Number.MAX_SAFE_INTEGER;if(b>=(a[c].viewport.ge||0)&&b<e)return c}},qb:function(a,b){return a.reduce(function(a,e){(a[e[b]]=a[e[b]]||[]).push(e);return a},{})},Lb:da,Jb:ca,Kb:ba,kb:function(a,b,c){switch(void 0===b?"SCRIPT":b){case "SCRIPT":return ba(a);case "IFRAME":return ca(a,void 0===c?"1x1":c);case "TRACK":return da(a);case "SCRIPT_BLOCK":return a?'<script type="text/javascript">'+a+
"\x3c/script>":"";default:return""}},za:O,Ib:function(a){var b=/^\d{1,4}x\d{1,4}$/;return"string"===typeof a&&b.test(a)?a.split("x").map(qa):a},ub:function(a,b){var c={},e;for(e in a)-1===b.indexOf(e)&&(c[e]=a[e]);return c},Ua:function(a){try{return"string"!==typeof a?void 0:h.document.cookie.split("; ").reduce(function(a,c){c=c.split("=");c=T(c);for(var b=c.next().value,k,d=[];!(k=c.next()).done;)d.push(k.value);a[b]=d.join("=");return a},{})[a]}catch(b){}},Ra:function(a,b){b||(b=h.location.href);
b=decodeURI(b);a=a.replace(/[\[\]]/g,"\\$&");return(a=(new RegExp("[?&]"+a+"(=([^&#]*)|&|#|$)")).exec(b))?a[2]?decodeURIComponent(a[2].replace(/\+/g," ")):"":null},Fb:aa,zb:function(a){void 0!==h.performance&&"function"===typeof h.performance.setResourceTimingBufferSize&&h.performance.setResourceTimingBufferSize(a)},once:P};F.prototype.tb=function(a,b,c,e){c=void 0===c?"sbi_"+z():c;e=void 0===e?{}:e;var k=this;a=a.replace("%%callback%%",c);return new Promise(function(d){var f=setTimeout(d,k.timeout,
e),g,p=P(function(a){clearTimeout(g);clearTimeout(f);if(null==b)d(a);else{var c={};c[b]=a;d(c)}});h[c]=p;k.ua("script",{src:a}).then(function(){g=setTimeout(function(){p(e)},500)})})};F.prototype.Ma=function(a,b,c){c=void 0===c?{}:c;return new Promise(function(e,k){function d(){4===f.readyState&&e(f.responseText)}var f,g=c.method||(b?"POST":"GET"),E=h.XDomainRequest&&(!h.XMLHttpRequest||void 0===(new h.XMLHttpRequest).responseType);E?(f=new h.XDomainRequest,f.onload=function(){e(f.responseText)},
f.onerror=function(){k("xhr on error")},f.ontimeout=function(){k("xhr timeout")},f.onprogress=function(){}):(f=new h.XMLHttpRequest,f.onreadystatechange=d);if("GET"===g&&b){var l=ua(a);Object.assign(l.search,b);a=va(l)}f.open(g,a);E||(c.withCredentials&&(f.withCredentials=!0),c.dc&&f.setRequestHeader("X-Requested-With","XMLHttpRequest"),f.setRequestHeader("Content-Type",c.contentType||"text/plain"));f.send("POST"===g&&b)})};F.prototype.ua=function(a,b){return new Promise(function(c,e){var k;if("image"===
a)k=Object.assign(new Image,b);else if("script"===a||" iframe"===a)k=h.document.createElement(a),Object.keys(b||{}).forEach(function(a){k[a]=b[a]}),h.document.head.appendChild(k);else return e();k.addEventListener?k.addEventListener("load",function(){c()}):k.readyState?k.onreadystatechange=function(){3===k.readyState&&c()}:e()})};var Q=[];I.prototype.log=function(a,b,c,e){e=null!=e?e-this.navigationStart:0+h.performance.now();a={dateTime:e,time:e-0,id:b,service:a};a.Za=c||[];Q.push(a);this.a&&"logData"in
h.sbi_km&&(c=h.sbi_km.logData,this.f(c[a.id].service,a.time,c[a.id].template,a.Za))};I.prototype.b=function(){Q.sort(function(a,b){return a.time-b.time});return Q};I.prototype.f=function(a,b,c,e){var k=[a,b];a=c.apply(c,e);Array.isArray(a)?a.forEach(function(a){return k.push(a)}):k.push(a);h.console.log.apply(console,k)};I.prototype.h=function(){var a=this;this.a=!0;this.caller.ua("script",{src:this.qa.url+"/morpheus_console.js"}).then(function(){var b=h.sbi_km.logData;a.b().forEach(function(c){a.f(b[c.id].service,
c.time,b[c.id].template,c.Za)})})};M.prototype.b=function(a){if(a in this.a){var b=Array.from(arguments);b.shift();this.a[a].A.forEach(function(a){return a.apply(a,b)});this.a[a].once.forEach(function(a){return a.apply(a,b)});this.a[a].once=[]}};M.prototype.once=function(a,b){this.a[a]=this.a[a]||{A:[],once:[]};this.a[a].once.push(b)};M.prototype.A=function(a,b){this.a[a]=this.a[a]||{A:[],once:[]};this.a[a].A.push(b)};pa(t,M);t.prototype.Da=function(a,b,c,e,k){var d=this,f=this;return new Promise(function(g){f.c.log("sbi",
200032,[a]);a=d.f(a.w);a.rendering=!0;var h=c;e&&Object.keys(e).forEach(function(a){Array.isArray(e[a])||(e[a]=[e[a]]);h=h.replace("%%"+a+"%%",e[a].join(","))});k?b.postMessage({creative:h,message:"SBI_RENDER"},"*"):b.document.write(h);f.c.log("sbi",200033,[a]);g(a)})};t.prototype.j=function(a){var b=a.getTargetingMap(),b=Object.keys(b).filter(function(a){return"sbi"===a.substr(0,3)});0<b.length&&b.forEach(function(b){a.clearTargeting(b)})};t.prototype.f=function(a){var b=this;return this.i().find(function(c){return b.h(c)===
a})||null};t.prototype.h=function(a){return a&&"getSlotElementId"in a?a.getSlotElementId():null};t.prototype.i=function(){return this.l.getSlots()};t.prototype.G=function(a){return a.getAdUnitPath()};t.prototype.v=function(a){return this.xa(a).map(function(a){return a.Cb+"x"+a.rb})};t.prototype.xa=function(a){a=a.getSizes.apply(a,fa());a=Array.isArray(a)?a:[];return a.filter(function(a){return"function"===typeof a.getWidth}).map(function(a){return{Cb:a.getWidth(),rb:a.getHeight()}})};t.prototype.Ja=
function(a,b){a=this.f(a);if(null!=a)for(var c in b)null!=c&&null!=b[c]&&a.setTargeting(c,b[c])};t.prototype.Bb=function(){var a=this,b=h.googletag.debug_log.log;h.googletag.debug_log.log=function(){var c=b.apply(h.googletag.debug_log,arguments);a.b("log",["dfp",c.getMessage().getMessageId()+1E5,c.getMessage().getMessageArgs(),c.getTimestamp().getTime()])}.bind(h.googletag.debug_log)};t.prototype.Ka=function(){this.l.updateCorrelator()};t.prototype.vb=function(){var a=this,b=h.googletag.defineSlot;
h.googletag.defineSlot=h.googletag.defineUnit=function(){"/"!==arguments[0].charAt(0)&&(arguments[0]="/"+arguments[0]);var c=b.apply(this,arguments);if(c){var e=c.getAdUnitPath;c.getAdUnitPath=function(a){a=e.call(this,a);return("/"!==a.charAt(0)?"/":"")+a};a.F&&a.b("slotsDefined",[c])}return c};var c=h.googletag.defineOutOfPageSlot;h.googletag.defineOutOfPageSlot=function(){"/"!==arguments[0].charAt(0)&&(arguments[0]="/"+arguments[0]);var b=c.apply(this,arguments);if(b){var e=b.getAdUnitPath;b.getAdUnitPath=
function(a){a=e.call(this,a);return("/"!==a.charAt(0)?"/":"")+a};b.isOutOfPage=!0;a.F&&a.b("slotsDefined",[b])}return b};var e=h.googletag.destroySlots;h.googletag.destroySlots=function(){var b=arguments.length?arguments[0]:a.l.getSlots();a.b("slotsDestroyed",b);return e.apply(this,arguments)};this.sa=this.l.refresh;this.l.refresh=function(){var b=Array.from(arguments),c={};0<b.length&&Array.isArray(b[0])?0===b[0].length?c.C=[]:(c.C=[],b[0].forEach(function(b){b&&"object"===typeof b&&"function"===
typeof b.getSizes?c.C.push(b):a.c.log("sbi",200036,[b])})):c.C=a.i();c.done=function(){a.c.log("sbi",200029,[c.C]);a.sa.apply(a.l,b)};c.C.forEach(function(b){a.j(b)});a.b("slotsRequestingRender",c)};this.ra=h.googletag.display;h.googletag.display=function(){if(a.F){var b=Array.from(arguments),c=a.ga({w:b[0]});null==c?a.ra.apply(h.googletag,b):c.ta||(c.ta=!0,a.ra.apply(h.googletag,b));if(!a.ca.Na)if(a.ca.Oa){if(c&&c.ta){var e=a.ya({wa:!1}),k=z();a.oa[k]={};if(0<Object.keys(e).length){Object.keys(e).forEach(function(a){e[a].wa=
!0});a.oa[k]=e;var b=Object.keys(e).map(function(b){return a.f(e[b].w)}),d={};d.C=b;d.done=function(){var b=a.oa[k],c=Object.keys(b).map(function(c){return a.f(b[c].w)});a.c.log("sbi",200029,[d.C]);a.sa.apply(a.l,[c,{changeCorrelator:!1}])};d.C.forEach(function(b){a.j(b)});a.b("slotsRequestingRender",d)}}}else if(0<b.length){if(c=a.ga({w:b[0]}))c.wa=!0;if(b=a.f(b[0]))a.c.log("sbi",200030,[b]),a.l.refresh([b],{changeCorrelator:!1})}}else a.c.log("sbi",200035,[arguments[0]]),a.la.push(arguments[0])};
var k=h.googletag.enableServices;h.googletag.enableServices=function(){var b=this,c=arguments;a.c.log("sbi",200031);a.F||(a.F=!0,a.l.disableInitialLoad(),a.b("initialized",a.i(),function(){k.apply(b,c);a.c.log("sbi",200034,[a.la.toString()]);a.la.forEach(function(a){return h.googletag.display(a)});a.la=[]}))};var d=this.l.enableSingleRequest;this.l.enableSingleRequest=function(){a.F||(a.ca.Oa=!0);d.apply(this,arguments)};var f=this.l.disableInitialLoad;this.l.disableInitialLoad=function(){a.F||(a.ca.Na=
!0);f.apply(this,arguments)};var g=this.l.enableAsyncRendering;this.l.enableAsyncRendering=function(){a.F||(a.ca.lb=!0);g.apply(this,arguments)}};t.prototype.Ca=function(a){return a.hasOwnProperty("isOutOfPage")&&a.isOutOfPage};y.prototype.v=function(a){this.j=a};y.prototype.i=function(a){var b={};a=T(a);for(var c=a.next();!c.done;c=a.next()){var c=this.b.h(c.value),e=null,k;for(k in this.a)if(this.a[k].w===c){e=this.a[k].id;break}null!=e&&(b[e]=this.a[e])}return b};y.prototype.h=function(a){var b=
this,c={},e={};a.forEach(function(a){var k=b.b.h(a),d=b.b.G(a);if(!(k in e)){c[d]=c[d]++||1;var f=z();e[f]={o:d,kc:d+":"+c[d],w:k,id:f,jc:!1,ac:!1,aa:!1,Xa:{},fa:[],fb:{},sizes:b.b.v(a),Ia:{},Zb:b.b.Ca(a),xa:b.b.v.bind(b.b,a),wa:!1,ta:!1,Gb:0}}});this.a=Object.assign(this.a,e)};y.prototype.Ab=function(a){for(var b in a)if(b in this.a){var c=this.a[b].w;this.a[b].fb=a[b];this.a[b].Ia=a[b].targeting;var e=Object.assign({},this.f.fa)[a[b].id];e&&(e.Y=a[b].creative,e.size=a[b].size,e.Ia=a[b].targeting,
this.a[b].Ia.sbi_size=a[b].size,this.b.Ja(c,a[b].targeting))}};x.Object.defineProperties(y.prototype,{C:{configurable:!0,enumerable:!0,get:function(){return this.a},set:function(a){this.a=a}}});K.prototype.ja=function(a){return a?this.a[a]:this.a};B.prototype.Z=function(a,b){if(a){a=this.a[a];if(b){var c=a[b];q.Ba(b)&&!c?a=this.P.ja(b):a=c}return a}return this.a};A.prototype.Qa=function(a){var b=a.key;a=this.b[void 0===a.m?this.m:a.m];if(b){var c=a[b];q.Ba(b)&&!c?a=this.H.Z(q.ia(this.H.Z()),b):a=
c}return a};A.prototype.$=function(a){var b=a.name;return this.i({m:void 0===a.m?this.m:a.m,J:void 0===a.J?"requestSettings":a.J}).find(function(a){return a.name===b})};A.prototype.ob=function(){return(this.j()||"https").replace(":","").replace("//","")};A.prototype.j=function(){var a={name:"protocol"};return(a=this.$({name:a.name,J:void 0===a.J?"requestSettings":a.J,m:void 0===a.m?this.m:a.m}))?a.value:void 0};A.prototype.i=function(a){var b=[];a=this.b[void 0===a.m?this.m:a.m][void 0===a.J?"requestSettings":
a.J]||[];for(var c=0;c<a.length;c++){var e=a[c];if(e.hasOwnProperty("dimensions")){var k="*";this.H.a&&(k=q.ia(this.H.Z()));Y(e)&&X(e,k)&&b.push(e)}else b.push(e)}return b};x.Object.defineProperties(A.prototype,{h:{configurable:!0,enumerable:!0,get:function(){var a="false"===q.Ra("sbi_"+this.m)?!1:!0,b="*";this.H.a&&(b=q.ia(this.H.Z()));var c=1;"number"===typeof this.a.frequency&&(c=this.a.frequency);return a&&!this.a.disabled&&this.G(this.a,b,"platforms")&&this.v(this.a,"domain")&&Math.random()<=
c}}});V.prototype.start=function(a,b,c){this.a||(this.c=c,a.Qa({}),this.L=a,this.a=!0,c.log("sbi",200011,[this.name]),this.b=this.Ga(a,b,c)||Promise.resolve({}));return this.b};J.prototype.clone=function(){return Object.assign(Object.create(this),this)};J.prototype.ha=function(a){var b=this.clone();switch(a){case 1:a={buyerid:b.S,buyername:b.ea,adunit_code:b.R,pageViewId:b.U,bidid:b.da,p:1,response:b.W,s:b.X||"0x0",bid:b.V,latency:b.ka,jsLatency:b.T};break;case 2:a={buyerid:b.S,buyername:b.ea,adunit_code:b.R,
pageViewId:b.U,bidid:b.da,p:2,response:b.W,s:b.X||"0x0",bid:b.V,latency:b.ka,jsLatency:b.T};b.I&&"string"==typeof b.I&&(a.dealid=b.na);break;default:a={buyerid:b.S,buyername:b.ea,adunit_code:b.R,pageViewId:b.U,bidid:b.da,p:3,response:b.W,s:b.X||"0x0",bid:b.V,latency:b.ka,jsLatency:b.T}}return a};x.Object.defineProperties(J.prototype,{id:{configurable:!0,enumerable:!0,get:function(){return this.da}},wb:{configurable:!0,enumerable:!0,get:function(){return this.U},set:function(a){this.U=a}},o:{configurable:!0,
enumerable:!0,get:function(){return this.j},set:function(a){this.j=a}},type:{configurable:!0,enumerable:!0,get:function(){return this.v},set:function(a){this.v=a}},hb:{configurable:!0,enumerable:!0,get:function(){return this.R},set:function(a){this.R=a}},g:{configurable:!0,enumerable:!0,get:function(){return this.V},set:function(a){this.V=a}},B:{configurable:!0,enumerable:!0,get:function(){return this.ea}},Va:{configurable:!0,enumerable:!0,get:function(){return this.i},set:function(a){this.i=a}},
G:{configurable:!0,enumerable:!0,get:function(){return 0>=this.a||!this.a?-1:this.a},set:function(a){this.a=Math.round(a)}},ka:{configurable:!0,enumerable:!0,get:function(){return 0>=this.a||!this.a?-1:Math.round(this.a)},set:function(a){this.a=Math.round(a)}},sb:{configurable:!0,enumerable:!0,get:function(){return Math.round(this.T)},set:function(a){this.T=Math.round(a)}},size:{configurable:!0,enumerable:!0,get:function(){return this.X},set:function(a){this.X=Array.isArray(a)?a.join("x"):a}},pa:{configurable:!0,
enumerable:!0,get:function(){return this.S},set:function(a){this.S=a}},Y:{configurable:!0,enumerable:!0,get:function(){return this.b},set:function(a){this.b=a}},I:{configurable:!0,enumerable:!0,get:function(){return this.na},set:function(a){this.na=a}},N:{configurable:!0,enumerable:!0,get:function(){return this.f},set:function(a){this.f=a}},response:{configurable:!0,enumerable:!0,get:function(){return this.W},set:function(a){this.W=a}},va:{configurable:!0,enumerable:!0,get:function(){return this.h},
set:function(a){this.h=a}}});var ja={sonobi:new V({Ga:function(a,b,c){this.L=a;this.K=b;this.c=c;this.c.log("sbi",200022,["sonobi"]);this.ma=!1;this.Ha=null},request:function(a,b,c,e){function k(){return Promise.resolve()}var d=this,f=this;c={};var g={},l;for(l in a)if(null!=a[l]&&Object.keys(a[l]).length){var m=a[l],n=m.o+"|"+encodeURIComponent(m.w);c[n]=m.sizes.join(",");g[n]=new J(m.sizes[0],"sonobi","sonobi",l,m.o,this.K,b)}b=encodeURIComponent(JSON.stringify(c));l=D(this.L);c=this.L.ob()+"://apex.go.sonobi.com/trinity.js?key_maker=";
var r=q.Sa(),t=c+b+"&cv=%%callback%%"+l+("&s="+r);f.c.log("sbi",200023,["sonobi",a]);b=this.L.$({name:"pubid"});null!=b&&null==q.Ua("sbi_user_sync_complete")&&(k=this.caller.ua.bind(this.caller,"script",{src:"https://sync.go.sonobi.com/uc.js?pubid="+b.value}),b=new Date,b.setTime(Number(b)+12096E5),h.document.cookie="sbi_user_sync_complete=true; expires="+b.toUTCString()+"; path=/");var v=this.L.$({name:"sovrnS2S"});this.c.log("sbi",200023,["sonobi",a]);return function(){return new Promise(function(a){if(!f.ma&&
v){var b=v?parseInt(v.value):100;f.caller.Ma.call(f.caller,"https://ap.lijit.com/readerinfo?loc="+h.location.hostname,{},{withCredentials:!0,method:"GET"}).then(function(b){b=JSON.parse(b);f.ma=!0;var c=[],e;for(e in b)c.push(e+"="+b[e]);f.Ha=c.join(";");a()}).catch(function(){f.ma=!0;a()});setTimeout(function(){f.ma=!0;a()},b)}else a()})}().then(k).then(function(){f.Ha&&(t+="&svt="+encodeURIComponent(f.Ha));return d.caller.tb.bind(d.caller,t)()}).then(function(b){d.c.log("sbi",200024,["sonobi",a,
b]);var c=q.nb(r);b=d.parse.call(d,b,a,c,g);e.M(b);return b})},parse:function(a,b,c,e){var d={},f;for(f in b)if(null!=b[f]&&Object.keys(b[f]).length){var g=b[f],h=g.o+"|"+g.w,l=g.o+"|"+encodeURIComponent(g.w);h in a.slots&&(l=e[l],h=a.slots[h],"sbi_aid"in h||(h={sbi_aid:null,sbi_apoc:null,sbi_size:null}),"sbi_dozer"in h||(h.sbi_dozer=!1),"sbi_pri"in h||(h.sbi_pri=10),"sbi_mouse"in h||(h.sbi_mouse=0,h.sbi_pri=1),l.g=100*parseFloat(h.sbi_mouse),l.size=h.sbi_size||l.size,l.I=h.sbi_dozer,l.type=h.sbi_ct||
l.type,l.N=parseInt(h.sbi_pri,10),l.ka=c,l.Va={sbi_aid:h.sbi_aid,sbi_dc:a.sbi_dc},l.Y=q.kb("//%%sbi_dc%%apex.go.sonobi.com/sbi.js?aid=%%sbi_aid%%&as=null","SCRIPT"),l.hb=g.o,h.sbi_dozer&&(l.va={sbi_dozer:h.sbi_dozer}),d[g.id]=[l])}this.c.log("sbi",200025,["sonobi",b,d]);return d},name:"sonobi",pa:"sonobi",bc:D,Qb:r,Pb:C,mc:"https://sync.go.sonobi.com/uc.js",lc:"https://ap.lijit.com/readerinfo?loc="})};f.prototype.f=function(a,b,c){var e=this,d=this.a[b].u;this.a[b].u[c].D||this.a[b].D?(Object.assign(this.a[b].u[c].xb,
a),"function"===typeof this.K.O&&Object.keys(a).forEach(function(b){a[b].forEach(function(a){a.response=2;e.K.O(a.ha(2))})}),this.a[b].u[c].D&&this.c.log("sbi",200037,[a]),this.a[b].D&&this.c.log("sbi",200038,[a])):(Object.assign(this.a[b].u[c].cb,a),d[c].ab=0,clearTimeout(this.a[b].u[c].Ea),0>=Object.keys(d).reduce(function(a,b){return a+=d[b].ab},0)&&(clearTimeout(this.a[b].Ea),this.h(b)))};f.prototype.h=function(a){var b=this.a[a].u,c=Object.keys(b).reduce(function(a,c){var e=b[c].cb;Object.keys(e).forEach(function(b){e[b].forEach(function(b){a[b.id]=
b})});return a},{});this.b=Object.assign(this.b,c);this.a[a].done(c)};f.prototype.M=function(a,b,c){var e=this;return function(d){var f=Math.round(h.performance.now()-b);Object.keys(d).forEach(function(a){d[a].forEach(function(a){a=e.i(q.Ra("sbi_price_"+c),a);a.ba=!1;a.sb=f})});e.f(d,a,c);return d}};f.prototype.i=function(a,b){a&&""!==b.Y&&0<b.g&&(b.g=parseInt(a,10));return b};f.prototype.$a=function(a,b,c,e,d){var f=this;this.c.log("sbi",200001,[c]);this.c.log("sbi",200006);this.a[e]={done:d,D:!1,
u:{},Ea:setTimeout(function(){f.c.log("sbi",200009);f.a[e].D=!0;Object.keys(f.a[e].u).forEach(function(a){f.a[e].u[a].D=!0});f.h(e)},c)};aa(b.adapterSettings).forEach(function(c){var d=c.name,k=new A(b,d);if(k.h){c=c.sizes;f.c.log("sbi",200011,[d]);var g={},l;for(l in a)if(a.hasOwnProperty(l)){a[l].sizes=a[l].xa();var p=ea(a[l].sizes,c);0<p.length&&(g[l]=Object.assign({},a[l]),g[l].sizes=p)}l=h.performance.now();var m=k.Qa({key:"timeout"});f.a[e].u[d]={cb:{},xb:{},wb:e,D:!1,ab:1,M:f.M(e,l,d),Ea:setTimeout(function(){f.c.log("sbi",
200008,[d,m]);f.f([],e,d);f.a[e].u[d].D=!0},m)};0<Object.keys(g).length?ja[d].start(k,f.K,f.c).then(function(a){ja[d].request(g,e,a,f.a[e].u[d])}):f.a[e].u[d].M({})}})};f.prototype.pb=function(a,b){if(0===a.length)return{};var c={};a.forEach(function(a){c[a.o]=c[a.o]||[];c[a.o]=c[a.o].concat(a)});a={};for(var e=T(Object.keys(c)),d=e.next();!d.done;d=e.next())if(d=d.value,0!==c[d].length){var f=ia.sonobiDealWinsOverHighestCPM(c[d],this.c);if(null!=f){f.La=!0;a[d]={targeting:{}};a[d].id=f.id;a[d].targeting.sbi_kmid=
f.id;a[d].targeting.sbi_bidder=f.B;a[d].targeting.sbi_ct=f.type;var g=ga(f.g,b);"number"===typeof g&&0<g&&(a[d].targeting.sbi_price=g);for(var h in f.va)a[d].targeting[h]=f.va[h];g=f.Y;g=ha(g,f.Va,"%%");a[d].creative=g;a[d].size=f.size}}this.c.log("sbi",200005,[a]);return a};x.Object.defineProperties(f.prototype,{fa:{configurable:!0,enumerable:!0,get:function(){return this.b},set:function(a){this.b=a}}});n.prototype.O=function(a){var b=this;this.a.length||setTimeout(function(){b.i(b.a);b.a=[]},100);
this.a.push(a)};n.prototype.h=function(a,b){var c=0;a.jb&&(c|=16);a.D&&(c|=8);a.La&&(c|=4);a.ba&&(c|=2);a.Aa&&(c|=1);switch(c){case 0:return 1;case 8:return 0;case 16:return 4;case 17:return 4;case 20:case 21:return this.c.log("sbi",200018,[b.g,b.B]),5;case 22:case 23:return 6;case 24:return 2;case 25:return this.c.log("sbi",200016),3;default:throw Error("Invalid bid status: "+c.toString(2)||"Assertion failed!");}};n.prototype.f=function(a){var b={g:0};a=T(a);for(var c=a.next();!c.done;c=a.next())c=
c.value,c.g>b.g&&(b=c);b.Aa=!0};n.prototype.M=function(a){this.f(a);a=T(a);for(var b=a.next();!b.done;b=a.next()){b=b.value;this.c.log("sbi",200026,[b.B,b]);var c={jb:0<b.g||b.I,D:b.Wb||b.Hb,La:b.La,ba:b.ba,Aa:b.Aa},d=void 0;try{d=this.h(c,b),b.response=d}catch(k){this.c.log(200020,[k.message])}this.O(b.ha(2))}};n.prototype.i=function(a){var b=void 0,b=void 0===b?this.b.ib.mb():b,c=this,d=q.qb(a,"pageViewId");Object.keys(d).forEach(function(a){var e=d[a].map(function(a){return q.ub(a,["pageViewId"])});
a=b+"?pageviewid="+a+"&corscred=1&ver="+h.sbi_km.version;e=JSON.stringify(e);return c.caller.Ma(a,e,{method:"POST"})})};l.prototype.mb=function(){var a=this.a.url;q.Ba("url")&&!a&&(a=this.P.ja("url"));return a};if(!h.hasOwnProperty("sbi_km")||!h.sbi_km.apiReady){q.zb(500);var R=new m(g),v=new I(g),S=new n(v,R),ka=new f(v,S),xa=h.sbi_morpheus=d(),la=h.sbi_km=h.sbi_km||{API:{debug:v.h.bind(v),getLog:v.b.bind(v)},config:g,apiReady:!1};h.addEventListener("message",function(a){"SAFE_FRAME_RENDER"===a.data.key&&
a.source&&h.sbi_km.API.render(a.source,a.data.id,a.data.macros,!0)},!1);v=new y(v,g,ka,S);v.v(wa(ka,g,R.P.ja("timeout"),v,R,S).yb);-1===h.location.search.indexOf("sbi_test")?h.document.cookie="sbi_debug=false":-1!==h.document.cookie.indexOf("sbi_debug=true")?la.API.debug(!0):-1!==h.location.search.indexOf("sbi_test")&&(h.document.cookie="sbi_debug=true",la.API.debug(!0));xa.initialize();h.sbi_km.apiReady=!0}}).call(this,window.sbi_config||{url:"//mtrx.go.sonobi.com",adServer:"dfp",globalSettings:{sizes:"300x250 300x600 300x1050 300x50 320x50 320x100 728x90 160x600 120x600 970x250 970x90 300x100 970x66".split(" "),
timeout:1600,priceRules:[{ge:3E3,set:3E3},{ge:900,lt:3E3,round:5},{lt:900,round:1}]},adapterSettings:[{name:"sonobi",sizes:"300x250 300x600 300x1050 300x50 320x50 320x100 728x90 160x600 120x600 970x250 970x90 300x100 970x66".split(" "),timeout:1500,disabled:!1,platforms:["mobile","desktop","tablet"],priceRules:[],parseSettings:[],requestSettings:[{name:"cdf",value:"guardian.ophan.pageViewId",dimensions:{sizes:[],adUnits:[],domains:[],platforms:[]}},{name:"ant",value:"guardian.config.page.appNexusPageTargeting",
dimensions:{sizes:[],adUnits:[],domains:[],platforms:[]}},{name:"pubid",value:"d089631d2d",dimensions:{sizes:[],adUnits:[],domains:[],platforms:[]}}]}],platformSettings:{mobile:{viewport:{lt:768}},tablet:{viewport:{ge:768,lt:992}},desktop:{viewport:{ge:992}}},analyticsSettings:{url:"https://keymaker.go.sonobi.com/keymaker",timeout:2E3}});window.sbi_km.version="3.10.1";}).call(window)
