---
title: "Tobit Lagged"
date: "August 20, 2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

printtab <- function(x) {
  x <- readr::read_csv(x)
  for (j in 1:ncol(x))
    x[is.na(x[,j]),j] <- ""
  knitr::kable(x)
}
```

# Summary statistics

```{r, results='asis'}
printtab("descriptive_stats.csv")
```

# Pvalues for Network effects of final model

```{r , results='asis'}
printtab("tobit_lagged_tabulate_model=Imp2010_report_rhos.csv")
```

# Full model

```{r , results='asis', comment=""}
for (i in c("05", "06", "08", "11", "13", "14")) {
  
  cat("\n\n## Article ", as.integer(i), "\n\n\n", sep="")
   
  print(printtab(
    sprintf("tobit_lagged_tabulate_model=Full-art=%s.csv", i)
  ))
  
}
```

# Final model

```{r , results='asis', comment=""}
for (i in c("05", "06", "08", "11", "13", "14")) {
  
  cat("\n\n## Article ", as.integer(i), "\n\n\n", sep="")
   
  print(printtab(
    sprintf("tobit_lagged_tabulate_model=Imp2010_report-art=%s.csv", i)
  ))
  
}
```
